### ISSUE TITLE
Order/Sorting of tests in the reports

### ISSUE THREAD

**Issue by jo-as** [pytest-dev/pytest-html#103]
Hello,

is there any way keep to original order of the tests. Currently I can sort for "Result", "Test" or "Duration". Unfortunately I do not have any unsorted order.. (so in the order were the test was executed).

The reason for that: 
we are performing many tests with fixture-parametrization (eg. 20 different tests on 100 test-cases), when several tests fails, it is quite difficult to analyze when we have only the ordered representation, but not the unsorted representation (in the sequence, where the tests were performed).

Thanks,
Best regards,
Josef

**Comment by davehunt** [comment]
I don't believe the test order is guaranteed by pytest at all. Also, if tests are running in parallel it would be difficult to represent the order in which they were run. This did come up before in #20. My suggestion at the time was to add a timestamp column for each test, which could then be sorted. Would this work for you?

**Comment by jo-as** [comment]
Hello,
thanks for your reply. 
The test-order is not guaranteed, thats clear. But it is difficult to follow the results in the html, when the order of the results in the html is not the same as the order of the test-execution.

A column with the execution-timestamp and the possibilty to sort for it would be perfect!

Best regards,
Josef

**Comment by davehunt** [comment]
@jo-as I've fixed this by allowing users to implement their own hooks to modify the results table, and given an example that adds a sortable timestamp. If you have some time, please take a look over #104. Hopefully I can release 1.14.0 soon with this enhancement.

**Comment by jo-as** [comment]
Hello,

I have tried your unreleased version and it works fine. The solution is perfect for our needs now (as we were using 1.9.0, we did not use the other benefits, yet.. especially the "show", "hide" feature).

Thanks for the work, it is a very useful plugin!

Best regards,
Josef

**Comment by davehunt** [comment]
Fixed by adding hooks in bc2e8a35554df68113cd2ae911dc396cd32cfe93 available in v1.14.0.
