### ISSUE TITLE
How to add additional content to Summary section?

### ISSUE THREAD

**Issue by shreyashah** [pytest-dev/pytest-html#109]
I need to add a Score value to the summary section in html report. There is a mention about how to add additional content to Environment section but not for summary. Please guide me on this.

I am developing a feature to score the test module based on the weightage given to test cases and applying mathematics to obtain the final score for the entire module. I need to print this score either in summary section or before the results  table.

**Comment by davehunt** [comment]
Interesting, though the summary section is not limited to a module, it represents the entire test session. It sounds like you'll need a new hook for extending the summary section. Please feel free to open a pull request introducing a `pytest_html_results_summary` hook. You could either try to add a structure, so this hook gets a list of key, value pairs for the label and value, or just pass around the containing element from the HTML. Note that there's associated JavaScript here for filtering so you'd want to ensure that doesn't break. Another option might be a simple `pytest_html_results_prefix` hook that by default is empty, and allows you to just put whatever HTML you'd like.

**Comment by suchitha92** [comment]
I would like to acess the config data inside the pytest_html_results_summary hook to add the details of the command being invoked for the test as a part of summary. Something like to appear in the report after summary section"

**Summary**
2 tests ran in 3.31 seconds.

(Un)check the boxes to filter the results.

1 passed, 1 skipped, 0 failed, 0 errors, 0 expected failures, 0 unexpected passes

**Command to reproduce the test**
pytest -v --report=report.html --self-contained-html --preset 1"

Currently, there is only provision to add some generic string in the pytest_html_results_summary hook.

Please let me know on this
