### ISSUE TITLE
Add ability to create custom assets

### ISSUE THREAD

**Issue by liiight** [pytest-dev/pytest-html#113]
If such ability already exist and I missed it, I apologize.
I have some api calls using `requests` module. I want to add a CURL format of the request when the test fails.
I use the `metadata` plugin to inject my string:
```python
req = e.response.request
metadata['curl'] = request_to_curl(req)
```
Then I'm overriding the table as such:
```python
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            # only add curl on failure
            if item.config._metadata.get('curl'):
                report.curl = pytest_html.extras.text(item.config._metadata.get('curl'))
        report.extra = extra


@pytest.mark.optionalhook
def pytest_html_results_table_header(cells):
    cells.insert(3, html.th('CURL'))
    cells.pop()


@pytest.mark.optionalhook
def pytest_html_results_table_row(report, cells):
    cells.insert(3, html.td(report.curl, class_='col-links'))
    cells.pop()
```
This return the unprepared asset, which I would like to run using [create_asset](https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/plugin.py#L137).
Obviously I can duplicate its code, but if there was a way to do this natively, it would be great.

**Comment by davehunt** [comment]
If you append your value to `report.extra` then it should create an assert and link to it from the HTML report. You shouldn't need to create a new column just for this new content:

```python
import pytest


@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            extra.append(pytest_html.extras.text('content', 'CURL'))
        report.extra = extra
```

Here's a screenshot from the report generated using the above code in `conftest.py`:
![13fac7ff-3886-4781-9cc9-7b1bd36ed17d](https://cloud.githubusercontent.com/assets/122800/26055198/9ae701c0-3967-11e7-9888-b918168c9470.png)

**Comment by liiight** [comment]
Thanks, this will indeed work for me.
The docs mentioned nothing about creating URLs like this using a 2nd arg, probably worth adding.

Thanks for this great plugin!

**Comment by davehunt** [comment]
@liiight you're right, we should mention the optional arguments when constructing extras. It's the 'name' argument, which is common to most extras. The code is here: https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/extras.py. If you're interested in writing a patch for the documentation, I'd be happy to review/merge it.
