### ISSUE TITLE
INTERNALERROR> UnicodeEncodeError: 'ascii' codec can't encode characters in position 496-497: ordinal not in range(128)

### ISSUE THREAD

**Issue by tomga** [pytest-dev/pytest-html#114]
On some data exception from subject occurs. Part of backtrace is following:
```
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
INTERNALERROR>     _MultiCall(methods, kwargs, hook.spec_opts).execute()
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/pytest_html/plugin.py", line 462, in pytest_runtest_logreport
INTERNALERROR>     self.append_failed(report)
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/pytest_html/plugin.py", line 274, in append_failed
INTERNALERROR>     self._appendrow('Failed', report)
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/pytest_html/plugin.py", line 246, in _appendrow
INTERNALERROR>     result = self.TestResult(outcome, report, self.logfile, self.config)
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/pytest_html/plugin.py", line 113, in __init__
INTERNALERROR>     self.append_log_html(report, self.additional_html)
INTERNALERROR>   File "/usr/local/pyenv/local/lib/python2.7/site-packages/pytest_html/plugin.py", line 216, in append_log_html
INTERNALERROR>     for line in str(report.longrepr).splitlines():
INTERNALERROR> UnicodeEncodeError: 'ascii' codec can't encode characters in position 496-497: ordinal not in range(128)
```

I've managed to fix (or maybe just workaround) this issue locally with following diff:
```
diff --git a/pytest_html/plugin.py b/pytest_html/plugin.py
index afc6275..95814d7 100644
--- a/pytest_html/plugin.py
+++ b/pytest_html/plugin.py
@@ -213,7 +213,7 @@ class HTMLReport(object):
         def append_log_html(self, report, additional_html):
             log = html.div(class_='log')
             if report.longrepr:
-                for line in str(report.longrepr).splitlines():
+                for line in unicode(report.longrepr).encode('utf-8').splitlines():
                     if not PY3:
                         line = line.decode('utf-8')
                     separator = line.startswith('_ ' * 10)
```

**Comment by tomga** [comment]
I forgot to write that issue occurred on python2 and fix seems to work on this version. I don't know if problem exists on python3 and if the fix work/doesn't break on python3.

**Comment by davehunt** [comment]
😢 More encoding issues... Please could you submit a pull request with your fix and a test?

**Comment by tomga** [comment]
What is the proper way to run already implemented tests?

I did:
```
  virtualenv ~/projects/pytest-html/testenv
  . ~/projects/pytest-html/testenv/bin/activate
  python setup.py install
  cd testing/
  pip install ansi2html
  pytest 
```
and received:
```
collected 41 items 

test_pytest_html.py FFFFF.FFFFF.............FFFFFFFFFF..FFxF.
```
Is it normal? Without existing tests working properly I can't really understand how to write test for my problem.

**Comment by tomga** [comment]
with following patch (removing one line):
```
diff --git a/testing/test_pytest_html.py b/testing/test_pytest_html.py
index 547aeed..c3244aa 100644
--- a/testing/test_pytest_html.py
+++ b/testing/test_pytest_html.py
@@ -62,7 +62,7 @@ def assert_results(html, tests=1, duration=None, passed=1, skipped=0, failed=0,
     assert_results_by_outcome(html, 'error', errors, 'errors')
     assert_results_by_outcome(html, 'xfailed', xfailed, 'expected failures')
     assert_results_by_outcome(html, 'xpassed', xpassed, 'unexpected passes')
-    assert_results_by_outcome(html, 'rerun', rerun)
 
 
 class TestHTML:
```
results are better:
`test_pytest_html.py ........................FFFFFFFFFF..FFx..`

and many of those failing tests fail due to different value generated by: `hash_generator.hexdigest()`

**Comment by tomga** [comment]
Installing `pytest-rerunfailures` fixed situation much more (with clean sources):
`test_pytest_html.py ....................................FFx..`

**Comment by tomga** [comment]
Installing `pytest-xdist` fixed rest of tests:
`test_pytest_html.py ......................................x..`
but I think it would be much better to xfail all those tests without those plugins installed or loudly inform that they don't work without those two plugins. It would save me some time. Maybe I would have a test for my issue now :-)

**Comment by nicoddemus** [comment]
@tomga did you try using `tox`? Tox is usually considered the de-facto standard for running tests in Python projects as it will take care of creating an appropriate virtual environment and running the tests using the appropriate flags.

I just noticed that there's no information about that in the README, so I added one in #117. 👍

**Comment by tomga** [comment]
I didn't know about this tool. Unfortunately with `tox -e py27` it starts to spawn many python processes before result of `testing/test_pytest_html.py::TestHTML::test_environment_xdist_reruns` is printed.
Those processes are: `pytest-html/.tox/py27/bin/python2.7 -u -c import sys;exec(eval(sys.stdin.readline()))`.
I've killed tests when number of those processes was close to 200 and system started to become unresponsible. I don't have this problem with my manually created virtualenv and `tox -e py34` works ok too.
I'm running this on Debian 8 and tox version is `1.8.0 imported from /usr/lib/python3/dist-packages/tox/__init__.py`

**Comment by nicoddemus** [comment]
I see thanks!

Hmm 1.8.0 is quite old (Sep 24, 2014), so this might be resolved by updating the `tox` version you have installed, or creating a virtual environment and installing the latest tox on it (2.7.0).

Regardless, if `py34` is working that should be enough for you to test locally. Once you open the PR pytest-html will run a complete test in Travis. 😁

**Comment by tomga** [comment]
I have a problem with creating a testcase for this. To reproduce you need to have `longrepr` in `report` that has unicode characters. The only way I'm able to create such case is when using plugin from:
`https://github.com/okken/pytest-expect` (need to be installled from git because there is a different package with same name on pip). It uses internally `pytest_runtest_makereport` and creates `longrepr` value.

I don't really know pytest internals enough to do this and have to leave you this task. I hope you will be able to write proper test case for this.

If you manage to create such failing test I think I have a little better fix than the first one:

```
             if report.longrepr:
-                for line in str(report.longrepr).splitlines():
+                for line in report.longreprtext.encode('utf-8').splitlines():
                     if not PY3:
```

It uses `longreprtext` property instead of `unicode`. I found this property when I was trying to make a testcase.

**Comment by tomga** [comment]
Finallly I've found out how to make a testcase and made a pull request. Some tests are failing on configurations with pytest29 but not only mine so I assume it is acceptable. I think the problem is more with testcase itself than with a fix.

**Comment by tomga** [comment]
I've checked history on travis and it seems that previously all tests were passing. Is seems it is due to usage of `longreprtext` which is not available I think on `pytest29`. Would you wannt a copy of code of this property be made in `pytest-html` or a conditional for diffferent fix for `pytest29` version or some other solution?
