### ISSUE TITLE
New 1.15.0 version gives AttributeError: 'TestReport' object has no attribute 'longreprtext'

### ISSUE THREAD

**Issue by silvana-i** [pytest-dev/pytest-html#122]
With latest version of pytest-html 1.15.0 we are seeing this error:
`INTERNALERROR> AttributeError: 'TestReport' object has no attribute 'longreprtext'`
Same issue is not visible with the previous 1.14.2.

We use it in its most straight forward way. Calling it from py.test with `pytest --html=report.html`.

**Comment by nicoddemus** [comment]
1.15.0 now pytest 3, unfortunately this was not specified in `setup.py` (should be fixed by #123).

**Comment by davehunt** [comment]
I've merged #123 and tagged for a release of 1.15.1. Thanks @silvana-i and @nicoddemus!

**Comment by nicoddemus** [comment]
🎆
