### ISSUE TITLE
path too long on windows when saving report with screenshots

### ISSUE THREAD

**Issue by ngavrish** [pytest-dev/pytest-html#124]
I have following code to generate screenshots in reports
```
        if xfail or report.failed:
            **extra.append(pytest_html.extras.image(pytest.driver.get_screenshot_as_base64(), ''))**
            extra.append(pytest_html.extras.html('<div><h2 style="color: red; ">{}</h2></div>'.format(test_name)))
        elif report.passed:
            extra.append(pytest_html.extras.html(
                '<div><h2 style="color: black; text-decoration: underline">{}</h2></div>'.format(test_name)))
        pytest_html.extras.html('<div style="color: black; margin: 10px;">'.format(test_name))
        for step in test_steps:
            extra.append(pytest_html.extras.html('<p style="margin: 5px;">{}</p>'.format(step)))
        pytest_html.extras.html('</div>')
        report.extra = extra
```

And you have line in plugin.py where you get file content and validate if its path. And in my case file content contains binary representation of image. When windows is trying to validate this long path, it fails into INTERNAL ERROR.

INTERNALERROR>   File "c:\python36\lib\site-packages\pytest_html\plugin.py", line 112, in __init__
INTERNALERROR>     self.append_extra_html(extra, extra_index, test_index)
INTERNALERROR>   File "c:\python36\lib\site-packages\pytest_html\plugin.py", line 164, in append_extra_html
INTERNALERROR>     os.path.isfile(content):
INTERNALERROR>   File "c:\python36\lib\genericpath.py", line 30, in isfile
INTERNALERROR>     st = os.stat(path)
INTERNALERROR> ValueError: stat: path too long for Windows

**Comment by davehunt** [comment]
Thanks for the bug report. It sounds like we need to catch this exception.

**Comment by camillake** [comment]
@davehunt This issue could be resolved, please refer to https://github.com/pytest-dev/pytest/issues/291. More about windows path: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by davehunt** [comment]
pytest-html [1.16.1](https://pypi.python.org/pypi/pytest-html/1.16.1) has been released with a fix.
