### ISSUE TITLE
Tests failing because rerun plugin might not be present

### ISSUE THREAD

**Issue by g-bon** [pytest-dev/pytest-html#125]
[assert_results_by_outcome](https://github.com/pytest-dev/pytest-html/blob/master/testing/test_pytest_html.py#L65) makes all tests that use it fail.

The assertion is made false by the absence of rerun tests in the report when the plugin is missing.

**Comment by davehunt** [comment]
pytest-rerunfailures is a dependency for running the tests, as specified in [tox.ini](https://github.com/pytest-dev/pytest-html/blob/master/tox.ini#L13). You should be using `tox` to run the tests as [mentioned in the README](https://github.com/pytest-dev/pytest-html#contributing), and the plugin should be installed in the virtual environments it creates.
