### ISSUE TITLE
Chrome blocking data uri

### ISSUE THREAD

**Issue by micheletest** [pytest-dev/pytest-html#128]
I'm running Chrome 60 and cannot click to open any of the Links (Browser Log, Server Log, etc.) in my self-contained pytest-html report. This seems to be due to Chrome blocking top frame navigation to data urls.  See [here](https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM) for their developer discussion on this. The console error is ```Not allowed to navigate top frame to data URL:``` Workaround is to use firefox, or right click to open the URL in a new tab.

**Comment by davehunt** [comment]
Another workaround would be to avoid using the self-contained report. I'm not sure how we can support a self-contained report without using data URIs. I'll leave this open for now in case there are suggestions, but otherwise we might just need to put a notice in the README.

**Comment by micheletest** [comment]
We can probably close this. I've gotten used to right click to open within the self contained report :)
