### ISSUE TITLE
Text on successful execution

### ISSUE THREAD

**Issue by lcofre** [pytest-dev/pytest-html#130]
Awesome plugin, thanks for it!

I have a question: How can I show some text when the execution is successful?
my tests print() details and make asserts, but the report shows "No log output captured".

Thanks in advance for your help!

**Comment by davehunt** [comment]
@lcofre try adding `-r P` to your command line. This will report summary information for passing tests when they have output. From `pytest --help`:

```
  -r chars              show extra test summary info as specified by chars
                        (f)ailed, (E)error, (s)skipped, (x)failed, (X)passed,
                        (p)passed, (P)passed with output, (a)all except pP.
                        Warnings are displayed at all times except when
                        --disable-warnings is set
```

**Comment by lcofre** [comment]
Thanks @davehunt for the clear explanation. It worked perfectly!
