### ISSUE TITLE
Report fixture setup and teardown

### ISSUE THREAD

**Issue by iwanb** [pytest-dev/pytest-html#131]
Hi,
I would like to vizualize when fixtures are set up and teared down, the time they take, their output and if they failed.
I think they could be added in the Results section, filtered by default, around the tests.
It might add a lot of information, so it would look better along with #33 

Would you be open to such an enchancement? (It could be optional if needed.)
Do you see issues it might create? Would you do it in a different way?

**Comment by davehunt** [comment]
There are already command line options for showing these, as shown below from `pytest --help`:

```
  --setup-only          only setup fixtures, do not execute tests.
  --setup-show          show setup of fixtures while executing tests.
  --setup-plan          show what fixtures and tests would be executed but
                        don't execute anything.
```

I don't think any of this will be displayed in the HTML report though. I'd be happy to merge a patch that adds the fixture details to the HTML report when `--setup-show` is specified.

**Comment by david-fliguer-ws** [comment]
Hi, sorry for the bump but any news about this ?
In my case before the first test is run I do a series of actions and I want to output to the HTML report some information about it 
Any workaround that can be done by now in a more or less clean way ? (Like saving all the text in a variable and then adding it manually to the HTML) ?

**Comment by iwanb** [comment]
I have not really looked into it yet.

It should be easy to make a workaround adding to pytest-html extra content from the pytest_fixture_setup hook.

**Comment by thesupershan** [comment]
Just wanna bump this, any chance someone can look into a fix?

**Comment by csm10495** [comment]
I'm curious, if we see a 'teardown' event come in instead of a 'call' can we just delete the last row of html and create a new one then as if it had been a 'call'.. (Then also fix test counts).

**Comment by ruck94301** [comment]
Hi, with pytest 4.6.11, this is a problem in "captured logs", but not in "live logs".  Showing both live & captured logs,
`(pytest -r A --log-cli-level=DEBUG)`
note that the teardown logrecords are missing from captured logs, but not missing from live logs.
Is there a workaround that I'm not seeing?  OtherwiseI should use live log if it's important to me.
![image](https://user-images.githubusercontent.com/7874612/98179360-6ce72900-1eb3-11eb-9149-db95cac70e66.png)

**Comment by gnikonorov** [comment]
Hi @ruck94301. What version of this plugin are you using?

**Comment by ruck94301** [comment]
sorry, are you looking for 4.6.11 or something else?

**Comment by ruck94301** [comment]
oh right, I suppose the python version is important context for reproducing, sorry for not including that.
`============================= test session starts =============================
platform win32 -- Python 2.7.18, pytest-4.6.11, py-1.9.0, pluggy-0.13.1
`

**Comment by gnikonorov** [comment]
@ruck94301 is this an issue with pytest or pytest-html?

**Comment by ruck94301** [comment]
I'm saying pytest.  I'm not using pytest-html.  Maybe my observation helps explain the observation in pytest-html.
