### ISSUE TITLE
Improved list value in metadata table

### ISSUE THREAD

**Issue by rasmuspeders1** [pytest-dev/pytest-html#133]
Hi,
I have created a pull request with a proposal for a small enhancement.
metadata values which are lists (or list like)  of strings are currently just presented as one long concatenated string of all members in the list.
My proposed fix simply creates a comma separated string of with the list members.

pull request here: https://github.com/pytest-dev/pytest-html/pull/132

**Comment by tomer** [comment]
Since #132 is merged, I suggest resolving this issue. @davehunt
