### ISSUE TITLE
How to store more than one report in Jenkins?

### ISSUE THREAD

**Issue by ainomc** [pytest-dev/pytest-html#134]
Can I have more than one report per job in Jenkins?
I can generate current date and add it to name of report. But Jenkins use workspace for reports and rewrite it.

Is any way to store more than one report in Jenkins?

**Comment by RonnyPfannschmidt** [comment]
soun ds like a jenkins question - in general the way to go is an actual artifact storage that takes the artifacts out of the build dir and into a permanent storage - there should be jenkins plugins for that

**Comment by davehunt** [comment]
Check out the [HTML publisher](https://plugins.jenkins.io/htmlpublisher) plugin for Jenkins. You can publish multiple HTML reports and they'll appear as tabs in the output.
