### ISSUE TITLE
Adding log to HTML report when show details

### ISSUE THREAD

**Issue by nicoarg** [pytest-dev/pytest-html#135]
Hello there, I use these kind of test with pytest and the html pluging:

```
import logging
log = logging.getLogger(__name__)

def test_random(app_config):
    log.info("Random test")
    pass
```
Is there a way to get the output of log.info in the report? Even when the test is passed? I only get output when the test fails.

**Comment by davehunt** [comment]
@nicoarg can you try adding the pytest argument `-r=P`, which will show extra test summary for passing tests with output?

**Comment by nicoarg** [comment]
Hi Dave, I tried but I still get get "No log output captured" :(

**Comment by nicoarg** [comment]
I found a solution adding `--caputre=sys`.

**Comment by nicoarg** [comment]
You can close the issue if you want.

**Comment by davehunt** [comment]
Thanks
