### ISSUE TITLE
add custom test results to report

### ISSUE THREAD

**Issue by ohayak** [pytest-dev/pytest-html#144]
Hi, 
I have a test function like this:
```
def test_score():
    # load csv of one column
    x = PrettyTable()
    x.field_names = ['old','new']
    for val in column:
         new_val = some_func(val)
         x.add_row([val, new_val])
         assert val == new_val
   output = x.get_string() # i want to print this in report when test success
```
and many other functions using this pattern, I can't figure out a way to retrieve output value inside pytest_html_results_table_html hook.
Do you have any suggestions ?

Thank you

**Comment by davehunt** [comment]
You could store the values on `request.node` as demonstrated here:

**test_score.py**

```python
import pytest


@pytest.mark.parametrize('score', [1, 5, 10])
def test_score_request(request, score):
    request.node._score = score


def test_no_score():
    pass
```

**conftest.py**

```python
from py.xml import html
import pytest


@pytest.mark.optionalhook
def pytest_html_results_table_header(cells):
    cells.insert(2, html.th('Score'))


@pytest.mark.optionalhook
def pytest_html_results_table_row(report, cells):
    cells.insert(2, html.td(report._score))


@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    report._score = getattr(item, '_score', 0)
```

If you have several items, you could use a single dict to store them such as `request.node._metadata`.

The above created the following report for me:

![screenshot-2018-1-5 test report](https://user-images.githubusercontent.com/122800/34610905-267b7204-f21b-11e7-8819-4e8914245775.png)

**Comment by ohayak** [comment]
works like a charm, Thank you

**Comment by yinina** [comment]
hi , do you know how to add a url to the Links column of test results  table?

**Comment by h3tz** [comment]
> You could store the values on `request.node` as demonstrated here:
> 
> **test_score.py**
> 
> ```python
> import pytest
> 
> 
> @pytest.mark.parametrize('score', [1, 5, 10])
> def test_score_request(request, score):
>     request.node._score = score
> 
> 
> def test_no_score():
>     pass
> ```
> 
> **conftest.py**
> 
> ```python
> from py.xml import html
> import pytest
> 
> 
> @pytest.mark.optionalhook
> def pytest_html_results_table_header(cells):
>     cells.insert(2, html.th('Score'))
> 
> 
> @pytest.mark.optionalhook
> def pytest_html_results_table_row(report, cells):
>     cells.insert(2, html.td(report._score))
> 
> 
> @pytest.mark.hookwrapper
> def pytest_runtest_makereport(item, call):
>     outcome = yield
>     report = outcome.get_result()
>     report._score = getattr(item, '_score', 0)
> ```
> 
> If you have several items, you could use a single dict to store them such as `request.node._metadata`.
> 
> The above created the following report for me:
> 
> ![screenshot-2018-1-5 test report](https://user-images.githubusercontent.com/122800/34610905-267b7204-f21b-11e7-8819-4e8914245775.png)

many thanks

**Comment by gayyan523** [comment]
how this request.node sets the value for items in pytest_runtest_makereport . also i don want to add requests as a  param in testcases [lot of rework] just want to use it in a reusbale function inside the wrapper test called by main test ? any work around
