### ISSUE TITLE
Failures (fatal) in py.test are not showing in the HTML report

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-html#148]
Hi,
I'm using pytest-html and I saw that that there is a critical defect..

We are using the  `--continue-on-collection-errors parameter` to avoid breaking the build where there are any compile errors.

However, when looking into the html log, I see that it can't grab the error and present it.
In the *.xml file that py.test produces, I can see the fail..

Can you please aid?

##
Step to reproduce
1. create couple of test_ZZZ.py files with compiling error
2. run `python -m py.test  --continue-on-collection-errors parameter --html=results.html --self-contained-html --junitxml results.xml`
3. Compare the .xm results to the html results.

**Comment by Formartha** [comment]
Dave - you are the best :)

**Comment by davehunt** [comment]
No problem! I'm hoping to get a new release out today with this fix.
