### ISSUE TITLE
Custom metadata missing from environment table when all tests are skipped

### ISSUE THREAD

**Issue by mike-maliska** [pytest-dev/pytest-html#149]
If a user skips all tests then the 'Environment' table does not show in the html report.

**Comment by mike-maliska** [comment]
Sorry this is no longer an issue with version 1.16.1
I was still using 1.10.0

**Comment by mike-maliska** [comment]
Sorry this is no longer an issue with version 1.16.1
I was still using 1.10.0

**Comment by davehunt** [comment]
Thanks for using the plugin @mike-maliska! I'm glad your problem is resolved in the latest version. 😄

**Comment by mike-maliska** [comment]
:(  sorry need to reopen the issue in a new format.
It seems that if ALL tests are skipped the ENV section does show up but my custom fields to not.

I am running this fixture:
@pytest.fixture(autouse=True, scope='session')
def _environment(request):
    request.config._metadata[' Test Suite Name'] = my_test_suite_name

This added the custom row to the env table without any problem as long as 1 test runs.
if ALL tests are skipped then I just get the default table and my custom rows don't show up.

Mike

**Comment by davehunt** [comment]
Thanks @mike-maliska, and sorry that you've found a bug. I've labeled this as help wanted for now. Hopefully someone can fix this and introduce a test to prevent it from happening again.

**Comment by mike-maliska** [comment]
![all_tests_passing](https://user-images.githubusercontent.com/22179425/36913586-73ae0388-1e18-11e8-9f4b-7f243221b8c7.JPG)
![all_tests_skipped](https://user-images.githubusercontent.com/22179425/36913587-73bf9cba-1e18-11e8-9423-93b0db61918c.JPG)

**Comment by mike-maliska** [comment]
Thanks David, we will work around the issue for now.
We are parcing the html report to do metric gathering is how we stumble across it.
I don't think we should be running any suites where all test are skipped anyways :-)

**Comment by j19sch** [comment]
I did some testing and it seems the fixture is never executed.

In this example the exception is never raised :
```
import pytest


@pytest.fixture(autouse=True, scope='session')
def _environment(request):
    raise Exception()
    request.config._metadata['content'] = '{0}'


@pytest.mark.skip
def test_pass():
    pass
```
Comment out the `@pytest.mark.skip` and the exception is raised. So the source of this behavior is in pytest itself.

**Comment by j19sch** [comment]
@mike-maliska I submitted two PRs that would allow you to add the test suite name without running into this issue:
- https://github.com/pytest-dev/pytest-html/pull/151
- https://github.com/pytest-dev/pytest-html/pull/152

**Comment by mike-maliska** [comment]
Thank you!!

**Comment by davehunt** [comment]
> Comment out the `@pytest.mark.skip` and the exception is raised. So the source of this behavior is in pytest itself.

I suppose this makes sense, if all tests are skipped then there's no need to run the fixtures. I wonder if there's a way to force a session scoped fixture to run. @RonnyPfannschmidt do you know?

**Comment by davehunt** [comment]
Closing as the related pull requests were merged. Please reopen if there are still issues.
