### ISSUE TITLE
CSS fails to load in Safari on Mac

### ISSUE THREAD

**Issue by sgirolkar** [pytest-dev/pytest-html#155]
Thanks for this great plugin!

Noticed this issue when trying to load the testReport on Safari on my MacBook.
I am using Version 11.0.3 (13604.5.6) of safari on macOS High Sierra version 10.13.3.
The HTML report loads without formatting. The CSS is not loaded.

I can see this error in the safari console log. 
`Refused to load ...../assets/style.css because it does not appear in the style-src directive of the Content Security Policy.`

**Comment by sgirolkar** [comment]
i noticed this was a settings issue in our Jenkins.
On setting the right permission, it got resolved.
solution reference: https://stackoverflow.com/questions/35783964/jenkins-html-publisher-plugin-no-css-is-displayed-when-report-is-viewed-in-j/42382300

**Comment by davehunt** [comment]
If you don't want to compromise the security of your Jenkins instance, then you should be able to use the `--self-contained-html` command line option, as [mentioned in the README](https://github.com/pytest-dev/pytest-html#creating-a-self-contained-report).
