### ISSUE TITLE
feature request - open html log with closed details

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-html#157]
Hi there,
We have adopted pytest-html to view our tests.
However, when a test fails it open the html file in a way we can't read it (it prints out the entire stacktrace + logs we are writing during the test).

It would be appropriate if we can pass down a value to close the html details of a failed/errored test and not opening it by default.

Thanks,
Mor

**Comment by davehunt** [comment]
Currently any tests that have an outcome of 'Passed' are collapsed, to draw attention to the details of any results with unexpected outcomes:

https://github.com/pytest-dev/pytest-html/blob/35a610065e50b94db30b068950e50d28f9c3545b/pytest_html/resources/main.js#L83-L86

I'd be happy to review a patch that added a feature to collapse all results, though I'm not sure of the best approach. We could allow custom JavaScript via a hook to run after the report has loaded, or perhaps accept query string parameters for the report. Perhaps you have other ideas?

**Comment by Formartha** [comment]
Thank you @davehunt.
I'm not a Javascript developer, however, I could just remove the "if" and make it work. thing is, that as you said the user should decide about it.
I tend to think that we can enable passing of an external variable to the html parser.

I can design the way it should be, but not the actual implementation ..

**Comment by jacebrowning** [comment]
My use case (#167) would be improved if we simply hid 'Skipped' tests by default.

**Comment by davehunt** [comment]
> How about `?collapsed=Skipped,Errored`? I think I could work on something like that.

Sounds good, thanks @jacebrowning

**Comment by Formartha** [comment]
Any implantation is considered in the near future?

**Comment by jacebrowning** [comment]
@Formartha Yeah, I'm going to look into adding support for a query param to change the default filtering.
