### ISSUE TITLE
Custom environment table order

### ISSUE THREAD

**Issue by jacebrowning** [pytest-dev/pytest-html#158]
In Python 3.6+ or with `OrderedDict`, the config metadata can maintain its order to control the layout of the environment table. Would you consider an option to make `sorted()` optional in this line:

https://github.com/pytest-dev/pytest-html/blob/35a610065e50b94db30b068950e50d28f9c3545b/pytest_html/plugin.py#L468

**Comment by davehunt** [comment]
Id be happy to review a pull request, though if we can determine when the user has specified a type that maintains order and avoid adding any configuration options that would be great!

**Comment by jacebrowning** [comment]
Cool.

It might be as simple as `sys.version_info >= (3, 6) or isinstance(metadata, OrderedDict)`.

Or just the latter condition if we want to be more explicit. Do you have a preference?
