### ISSUE TITLE
question : get py.xml for enhancing the report

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-html#161]
Hi,

I tried searching for py.xml via any given site. however, I can't seem to find anything that meets this requirement. can someone help with it?

**Comment by RonnyPfannschmidt** [comment]
its part of pylib, by now we hope we can eventually get rid of it

**Comment by davehunt** [comment]
@Formartha documentation can be found here: http://py.readthedocs.io/en/latest/xml.html
