### ISSUE TITLE
html file is huge - need to understand how to manipulate it

### ISSUE THREAD

**Issue by Formartha** [pytest-dev/pytest-html#165]
Hi there,

I'm using the amazing py-html report file - however, I using a logge that prints out tons of information (I'm using py.test as an E2E testing tool for the entire platform. a lof for a given test could be 1000 lines).

My main issue is that I dont want all the log to be listed in html but rather link it to some NFS folder that I'll throw the zip files of the reports there and just link it to the html (modify the table, add link to a given folder and that's it).

How can I achieve this use-case easily?
I may need to start using debug levels in the logs?

**Comment by Formartha** [comment]
Plus,
How can I trigger filling out the 'links' section of the report?

**Comment by davehunt** [comment]
I would suggest redirecting your logs to file, and then including these as extras in the report. Here an example of adding a log file to the links section:

```python
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    pytest_html = item.config.pluginmanager.getplugin('html')
    with io.open('/path/to/log', 'r', encoding='utf8') as f:
        extra.append(pytest_html.extras.text(f.read(), 'Log'))
    report.extra = extra
```

Note that if you use `--self-contained-html` then the contents of the log file will be included in the HTML file, resulting in a much larger file size. If you do not specify this, then an `assets` directory will be used to store the log content.

**Comment by Formartha** [comment]
Thank Dave!
will try it and keep you posted.
