### ISSUE TITLE
dynamically create the output folder for report.html using command line in pytest

### ISSUE THREAD

**Issue by writetomaha14** [pytest-dev/pytest-html#169]
Is there any way to create the output folder dynamically for every run with current time stamp and report.hml should be available in that folder. 

Is it possible to pass thru the command line for the dynamic folder creation and report.html should be available once all the test cases are executed. 

Thanks for the help

**Comment by davehunt** [comment]
The destination directory is created if it doesn't exist, so you just need to specify the time stamp in your command. For example, the following works in bash:

```
$ pytest --html $(date +%s)/results.html test_fail.py
================================ test session starts =================================
platform darwin -- Python 3.6.4, pytest-3.6.0, py-1.5.3, pluggy-0.6.0
rootdir: /Users/dhunt/workspace/pytest-scratchpad, inifile:
plugins: metadata-1.7.0, html-1.19.0
collected 1 item

test_fail.py F                                                                 [100%]

====================================== FAILURES ======================================
_____________________________________ test_fail ______________________________________

    @pytest.mark.flaky(reruns=5)
    def test_fail():
>       assert False
E       assert False

test_fail.py:6: AssertionError
 generated html file: /Users/dhunt/workspace/pytest-scratchpad/1527855629/results.html
============================== 1 failed in 0.05 seconds ==============================
```

**Comment by davehunt** [comment]
> Is there any way we can configure the timestamp folder in conftest.py file , as i am storing the screenshots in the timestamp folder. if i can get this time stamp folder to generate the pytest report.html that would help me.

I'm assuming you're taking your own screenshots, and not talking about the ones taken by pytest-selenium, as those are already stored within the target directory? Any screenshots you add to the report as extras should also be stored in the target directory. If you still want to access the HTML directory then you can do so my using the `pytestconfig` fixture and calling `pytestconfig.getoption('html')`, which will give you the full destination path for the report.
