### ISSUE TITLE
pytest-html not able to collect tests when we run with another pypi package pytest-parallel

### ISSUE THREAD

**Issue by GowriShankariSurendran** [pytest-dev/pytest-html#179]
We use pytest-html to collect tests at the end of our test suite.
But when we use another pypi pacakge pytest-parallel (which runs tests in parallel - an alternative to xdist), the tests are not collected by pytest-html.
The console prints the correct tests run, but pytest-html is not able to collect them.
As an example, this is the following pytest- commands which I run
 py.test --workers 2 -m "ewlc" -sv com/tests/mock/e2e/eWLC_Client_Issues/blacklist_dhcp_eWLC_Issues_test.py -k test --config device_mock_Cluster.yaml --html=local-regression.html

PIP list is as follows
pip list | grep pytest
pytest                3.8.0      
pytest-assume         1.2        
pytest-cov            2.2.1      
pytest-dependency     0.3.2      
pytest-forked         0.2        
pytest-html           1.19.0     
pytest-metadata       1.7.0      
pytest-mock           0.10.1     
pytest-ordering       0.5        
pytest-parallel       0.0.5      
pytest-xdist          1.23.0 

Console output for tests is 
============================================================================================ 27 passed, 108 warnings in 12.59 seconds =============================================================================================

Image of the HTML file generated for that run.

<img width="974" alt="screen shot 2018-09-26 at 3 18 11 pm" src="https://user-images.githubusercontent.com/43553700/46112394-6bf55080-c19f-11e8-9d23-1e0fc624a64c.png">

Can someone please take a look at it and see if there are any fixes available

**Comment by BeyondEvil** [comment]
Since we haven't heard anyhing from @GowriShankariSurendran I'm going to close this.

Feel free to reopen if needed.
