### ISSUE TITLE
Passing selenium screenshots to the report

### ISSUE THREAD

**Issue by Vic152** [pytest-dev/pytest-html#186]
Hey Guys,

I have fixture for wedriver:
```
@pytest.fixture(scope='session')
def browser():

    driver = webdriver.Chrome('resources//chromedriver.exe', options=options)
    driver.get('http://www.gogle.com')
    driver.implicitly_wait(5)

    return driver
```

I have want to add extra in the report:

```
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':

        browser.save_screenshot('D:/report/scr.png')
        extra.append(pytest_html.extras.image('D:/report/scr.png'))

        # always add url to report
        extra.append(pytest_html.extras.url('http://www.example.com/'))
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            # only add additional html on failure
            extra.append(pytest_html.extras.image('D:/report/scr.png'))
            extra.append(pytest_html.extras.html('<div>Additional HTML</div>'))
        report.extra = extra

```

I get an error when I try to do this: **AttributeError: 'function' object has no attribute 'save_screenshot'**
It seems like I cannot pass webriver.

**Comment by Vic152** [comment]
Okay so here is how you access webdriver from the report generation hook:

@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):

    timestamp = datetime.now().strftime('%H-%M-%S')

    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':

        feature_request = item.funcargs['request']

        driver = feature_request.getfuncargvalue('browser')
        driver.save_screenshot('D:/report/scr'+timestamp+'.png')

        extra.append(pytest_html.extras.image('D:/report/scr'+timestamp+'.png'))

        # always add url to report
        extra.append(pytest_html.extras.url('http://www.example.com/'))
        xfail = hasattr(report, 'wasxfail')
        if (report.skipped and xfail) or (report.failed and not xfail):
            # only add additional html on failure
            extra.append(pytest_html.extras.image('D:/report/scr.png'))
            extra.append(pytest_html.extras.html('<div>Additional HTML</div>'))
        report.extra = extra

This will give you an error:

```
selenium.common.exceptions.WebDriverException: Message: chrome not reachable
  (Session info: chrome=61.0.3153.0)
  (Driver info: chromedriver=2.33.506120 (e3e53437346286c0bc2d2dc9aa4915ba81d9023f),platform=Windows NT 10.0.17134 x86_64)

```
But this can be easily fixed by checking if driver is present - this happens because driver closes before report is generated.

**Comment by chau11ece** [comment]
Hi
I got this error message when I run your code

INTERNALERROR>     driver.get_screenshot_as_file('D:/report/scr'+timestamp+'.png')
INTERNALERROR> AttributeError: 'str' object has no attribute 'get_screenshot_as_file'

Can you help  solve the problem.

Thanks,

**Comment by CosteaIonut89** [comment]
Hi
I go this error:
INTERNALERROR>     feature_request = item.funcargs['request']
INTERNALERROR> KeyError: 'request'

Can anyone help me too>

Thank you!

**Comment by Vic152** [comment]
> Hi
> I got this error message when I run your code
> 
> INTERNALERROR> driver.get_screenshot_as_file('D:/report/scr'+timestamp+'.png')
> INTERNALERROR> AttributeError: 'str' object has no attribute 'get_screenshot_as_file'
> 
> Can you help solve the problem.
> 
> Thanks,

Why is your `driver` of type string? I would try to solve this mystery to troubleshoot it.

**Comment by Vic152** [comment]
> Hi
> I go this error:
> INTERNALERROR> feature_request = item.funcargs['request']
> INTERNALERROR> KeyError: 'request'
> 
> Can anyone help me too>
> 
> Thank you!

It was a looong time since I wrote this code. I would try to understand what keys are in `item.funcargs`. 
Also, maybe this helps: [https://github.com/pytest-dev/pytest/issues/3455](https://github.com/pytest-dev/pytest/issues/3455)

**Comment by CosteaIonut89** [comment]
I don't know if is this because I am noob in automation but here is what I go on contest:
`@pytest.fixture()
def setup():
    driver = webdriver.Chrome(executable_path=r'E:\Python Projects\StackField\testCases\chromedriver.exe')
    return driver
`

**Comment by CosteaIonut89** [comment]
@Vic152 sorry but I forgot to mention you first time.
