### ISSUE TITLE
add markdown export

### ISSUE THREAD

**Issue by faroit** [pytest-dev/pytest-html#198]
I just discovered this package and I really like the generated outputs. Thanks for this great work!

However, sometimes a report, formatted in simple markdown would be good enough and could be easily posted in github issues.

* Is there anyone working on this?
* has anyone seen other pytest plugins that could produce markdown reports?
* Is this of any interest?

I would love to work on this, so I would appreciate appropriate hints or help with this initiative.

**Comment by hackebrot** [comment]
Hey @faroit! 👋 

I'm also interested in such a plugin and would be to work with you on that! I am planning to create a minimal plugin for Python 3 in the next couple of weeks to demo in an upcoming talk.

**Comment by faroit** [comment]
@hackebrot thanks, just ping me later if you need some help

**Comment by hackebrot** [comment]
https://github.com/hackebrot/pytest-md 📝
