### ISSUE TITLE
Page header does not take environment variables into account

### ISSUE THREAD

**Issue by MaximeWeyl** [pytest-dev/pytest-html#201]
In pytest.ini, I have : 

    addopts = --html $APPRENTI_MOTEUR_LOGS_DIR_TEST/$APPRENTI_MOTEUR_LOGS_HTML_NAME

The path of the html report takes the content of the environment variable into account.

But the page header does not :
![image](https://user-images.githubusercontent.com/31591159/56751616-c9c63700-6786-11e9-9df4-82e79475b3bb.png)

It would be nice if it would as well :-)

**Comment by BeyondEvil** [comment]
Thanks for reporting this! @MaximeWeyl 

However, I think this is a limitation (bug?) with pytest itself, and not the plugin. And I'm not really, at least initially, comfortable with solving the symptom.

Thoughts @nicoddemus ?

**Comment by nicoddemus** [comment]
Not sure, how does pytest-html get that header?

**Comment by BeyondEvil** [comment]
> Not sure, how does pytest-html get that header?

https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/plugin.py#L435

@nicoddemus

**Comment by MaximeWeyl** [comment]
I think the trick (used for the HTML report filename) is here :

        logfile = os.path.expanduser(os.path.expandvars(logfile))
        self.logfile = os.path.abspath(logfile)



Le jeu. 25 avr. 2019 à 23:18, Jim Brännlund <notifications@github.com> a
écrit :

**Comment by MaximeWeyl** [comment]
i feel like replacing session.config.option.htmlpath with self.logfile in
html.h1(os.path.basename(session.config.option.htmlpath)),
would work (but I have no computer to test it right now).

**Comment by nicoddemus** [comment]
`addopts` does not seem to expand environment variables at all:

```ini
[pytest]
addopts = %TEMP%
```

(I'm on Windows)

Results in:

```
ERROR: file not found: %TEMP%
```

Same if I use `$TEMP`.

As @MaximeWeyl just pointed all, this is the culprit:

https://github.com/pytest-dev/pytest-html/blob/27b6e77ab1f5417515a352a978f20b1952b9a8aa/pytest_html/plugin.py#L86-L90

So this line:

https://github.com/pytest-dev/pytest-html/blob/27b6e77ab1f5417515a352a978f20b1952b9a8aa/pytest_html/plugin.py#L435

Should be using the expanded string as well. 👍

**Comment by RibeiroAna** [comment]
I'm not sure I understand, but you want to write the whole path of the test file, not only the tittle, right? Because if is that, you can use just put out the basename thing from it, right? Or am I not seing something?

**Comment by BeyondEvil** [comment]
> `addopts` does not seem to expand environment variables at all:

Right, as I expected. So this is by design then, and not a bug?

If that's the case, I can create a PR with the suggested fix. :)

@nicoddemus

**Comment by BeyondEvil** [comment]
> I'm not sure I understand, but you want to write the whole path of the test file, not only the tittle, right? Because if is that, you can use just put out the basename thing from it, right? Or am I not seing something?

What's happening is that the environment variable isn't being expanded "in" the report. It's using the name of the env var instead.

@RibeiroAna

**Comment by nicoddemus** [comment]
> Right, as I expected. So this is by design then, and not a bug?

Exactly. 👍 

> If that's the case, I can create a PR with the suggested fix. :)

Sure, that would be great!

**Comment by BeyondEvil** [comment]
So, changing it to use `self.logfile` with:

`addopts = --html $HTMLREP.html` where `$HTMLREP` expands to "hello"

renders the entire path:
<img width="674" alt="Screen Shot 2019-04-26 at 00 37 10" src="https://user-images.githubusercontent.com/15611634/56772767-a5388200-67bb-11e9-9bdc-ab558583858e.png">

Is that the expected behaviour? 🤔 

@nicoddemus @MaximeWeyl

**Comment by nicoddemus** [comment]
Sorry, I wasn't clear, the line should be changed to this:

```python
html.h1(os.path.basename(self.logfile)), 
```

**Comment by BeyondEvil** [comment]
> Sorry, I wasn't clear, the line should be changed to this:
> 
> ```python
> html.h1(os.path.basename(self.logfile)), 
> ```

Oh, haha, duh! 😛 

I'm going to see if I can add a test for it as well. PR incoming! (Probably not tonight tho..)

**Comment by nicoddemus** [comment]
Sure, sounds good! 😁

**Comment by BeyondEvil** [comment]
PR in #203 

I would really appreciate it if @MaximeWeyl and/or @nicoddemus could test this also on a Win machine. 🙏

**Comment by MaximeWeyl** [comment]
It works !

![image](https://user-images.githubusercontent.com/31591159/56800169-b2388e00-681a-11e9-9ade-555bd69b4056.png)


I am on windows 10.
