### ISSUE TITLE
add url in result table 

### ISSUE THREAD

**Issue by yinina** [pytest-dev/pytest-html#202]
hi ,
    I want to add a url as a supplement to test description  in the Links column of result table, but can't, do you have any suggestions?

**Comment by BeyondEvil** [comment]
Hi @yinina !

Here's an example of how to do it:

https://github.com/pytest-dev/pytest-selenium/blob/master/pytest_selenium/pytest_selenium.py#L280

Cheers

**Comment by BeyondEvil** [comment]
Hi @yinina!

Since I haven't heard anything more, I'll go ahead and close this. Feel free to repopen it if you need.
