### ISSUE TITLE
error: unrecognized arguments: --self-contained-html

### ISSUE THREAD

**Issue by JoshSullivan11** [pytest-dev/pytest-html#204]
When I run my tests that previously worked with python 2.7 on python 3.5.2 I receive the following error:
`ERROR: usage: example_test.py [options] [file_or_dir] [file_or_dir] [...]
example_test.py: error: unrecognized arguments: --self-contained-html
  inifile: /home/joshsullivan/project_folder/pytest.ini
  rootdir: /home/joshsullivan/project_folder
`

I am using Bazel to run my test with the following command:
`bazel run :example_test -- --self-contained-html`

However I get the same output when I run
`pytest example_test.py --self-contained-html`

This is the environment I am running on and the installed packages
`platform linux -- Python 3.5.2, pytest-4.4.1, py-1.8.0, pluggy-0.9.0
rootdir: /home/joshsullivan
plugins: metadata-1.8.0, html-1.13.0
`

Before on 2.7, when I ran a test, at the end of the test would be an url link to that html file. Note that I am using pytest-html v1.13.0 which according to all the documentation should be compatible with my python 3.5.2 environment and the only thing that has change in my environment is the python version upgrade from 2.7 to 3.5.2.  Any help would be greatly appreciated as I have been looking at this issue for 3 days without any progress. Thank you in advance.

**Comment by BeyondEvil** [comment]
@JoshSullivan11 

Any particular reason why you're using 3.5.x instead of 3.6 or even 3.7?

With that said, would you mind sharing a reproducible test/code/repo?

**Comment by JoshSullivan11** [comment]
@BeyondEvil 

I didn't realize I still had this issue open. We ended up having to revert the version of Pytest back to a previous version and got it working again. Thank you for the reply. I will go ahead and close this issue.
