### ISSUE TITLE
extras from previous tests show up

### ISSUE THREAD

**Issue by fenchu** [pytest-dev/pytest-html#205]
![pytest-html-extras-still-inn](https://user-images.githubusercontent.com/11349883/58231278-e0848d00-7d36-11e9-8576-ef43aac4c761.png)

Why does the images show up in tests/test_02_exceptions.py?

I use fixture ext to keep track of my variables and the hookwrapper ads them if it finds anything in global extras['SCREENSHOTS'], it works fine for tests within the tests/test_01_connectivity.py file as you can see in the upper part of the png. but all from the last test in test_01_* file show up in the tests from the test_02_* file (lower part of png)

tests/test_02_exceptions.py:
```
@pytest.mark.usefixtures("ext")
def test_01_div_zero_exception(ext):
    """
    pytest.raises can assert that exceptions are raised (catching them)
    """
    ext = {}
    with pytest.raises(ZeroDivisionError):
        x = 1 / 0
        print("1/0 = {}".format(x))
```

conftest.py:
```
extras = None
@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    global extras
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    #print("extras:{}".format(extras))
    report = outcome.get_result()
    report.description = str(item.function.__doc__)
    extra = getattr(report, 'extra', [])
    if extras and extras.get('urls'):
        for u in extras['urls']:
            extra.append(pytest_html.extras.text("usr:{}".format(u)))
    if extras and extras.get('screenshots'):
        for sc in extras['screenshots']:
            extra.append(pytest_html.extras.image(sc, mime_type='image/png', extension='png'))
    report.extra = extra

@pytest.fixture(scope="session", autouse=True)
def ext():
    """ storage to pass from test to report, but does not follow scope, so need to clean in subsequent tests """
    global extras
    extras = {}
    yield extras
    extras = {}
    return extras
```

Any tip on how to do this better is also very appreciated.

**Comment by fenchu** [comment]
it works if I change the code in tests_02_exceptions.py:
```
@pytest.mark.usefixtures("ext")
def test_01_div_zero_exception(ext):
    """
    pytest.raises can assert that exceptions are raised (catching them)
    """
    if ext: #need to clean all keys, but not the reference
        for k in list(ext.keys()):
            ext[k] = None
    with pytest.raises(ZeroDivisionError):
        x = 1 / 0
        print("1/0 = {}".format(x))
```
How can I create a fixture class this works for. I tried wrapping anything into testclasses, and used scope="class" and dropping fixture ext on test_02_* file, but it was the same.

**Comment by BeyondEvil** [comment]
Hi @fenchu 

So, lots of things going on here. I'll try to sort at least some of them out. :)

The reason why the screenshots in `extras` is showing up in `tests/test_02_exceptions.py` is because the fixture (`ext`) is `session` scoped.

Also, you're sort of mixing three different concepts/types when it comes to fixtures. You're using `autouse`, `@pytest.mark.usefixtures`, _and_ calling the fixture in the test function definition. They're meant to be used sort of "either or". I'm not sure if mixing them will cause any issues - but there's no point in doing it.

You can read more about fixtures [here](https://docs.pytest.org/en/latest/fixture.html).

**Comment by fenchu** [comment]
Thanks for the feedback, @BeyondEvil, 
Reason for the global extras was to get data somehow into pytest_runtest_makereport() but if I can use the item.node for it it will be much better.

I'm not using pytest-selenium, but will try it out.

**Comment by BeyondEvil** [comment]
You're welcome @fenchu! :)

I'll close this issue since it's not really a pytest-html one. Feel free to reach out to me here or on Slack (jimboslice).
