### ISSUE TITLE
pytest html report to open results collapsed based on option given

### ISSUE THREAD

**Issue by cauvery** [pytest-dev/pytest-html#206]
I am looking for option on how to open the html report with all results collapsed.  By default only Passed results are collapsed and all others are expanded in html report from Jenkins.  
 
I did go through the doc in pytest-html where it says to use the query parameter for report.hml. But how to achieve this dynamically from may be from conftest.py.  Need information. 
Thanks in advance. 

Versions I am using are:
pytest-html 1.15.1
pytest 3.2.5.

**Comment by cauvery** [comment]
Sounds right, thanks @nicoddemus.

**Comment by BeyondEvil** [comment]
Hi @cauvery and thanks for the report!

Help me understand why using the query param isn't enough.

**Comment by cauvery** [comment]
Hi @BeyondEvil, 

I am not sure how I can invoke the query param from within the pytest script for report to be opened with all results collapsed.  I can navigate to the report location from Jenkins and issue the query param for results to be collapsed (same as clicking on Hide all Results on HTML Report), just not sure how to use it dynamically. 

Thanks,
Cauvery.

**Comment by BeyondEvil** [comment]
@cauvery 

My answer here is going to based on two assumptions:
1.  That you're generating the name of the report somewhere and that you own/control when and where that happens.
2. That you're generating the link to the report that shows up in Jenkins and that that it is also under your control.

If the above is true, you can then dynamically change either the name or more likely the link-generation to add the query param.

Note that this doesn't necessarily have to happen from within pytest, but can be done for example in any scripts (bash or otherwise) that run before or after pytest.

Hope that helps.

**Comment by cauvery** [comment]
Thanks @BeyondEvil  I get and agree on what you are saying. Will try from within Jenkins job configuration to open the report with query parameters.  

Thanks,
Cauvery.

**Comment by alexandru-patrascu-mpf** [comment]
@cauvery  did you manage to do it? Please share the details, as I am also interested in the solving this. In my case, all tests are expanded. Thanks!

**Comment by BeyondEvil** [comment]
> @cauvery did you manage to do it? Please share the details, as I am also interested in solving this. In my case, all tests are expanded. Thanks!

Maybe this (recently added) will solve it for you: https://github.com/pytest-dev/pytest-html#display-options

**Comment by alexandru-patrascu-mpf** [comment]
Hi @cauvery, thanks for the response. I did try, did not work for me either. Guess will have to wait until someone finds a solution to our problem. Thanks again!

**Comment by cauvery** [comment]
Hi @alexandru-patrascu-mpf  it actually worked for me from Jenkins.  Though it did not work locally from my mac.  Will try later again locally and see if it worked locally too.  

Its the display option I referring to that worked from Jenkins.

**Comment by BeyondEvil** [comment]
I'm sorry you're experiencing this problem @bkashigar.

It's been fixed in the next major version.

Hold tight and thanks for understanding!
