### ISSUE TITLE
--html=mydir/report.html - get hold of dir for extras

### ISSUE THREAD

**Issue by fenchu** [pytest-dev/pytest-html#207]
Hi

Is there a way you can get hold of the --html setting within my pytest tests. I need it to set master directory for all the extras I add. Most CIs do not allow showing html reports anymore, So I need to pack it and pipe to a webservice.

This is very apparent when you use 
`@pytest.mark.parametrize("webhost", <array of testservers>)`

currently I use:
`_dir_ = os.path.basename(__file__).replace('.py', '') + '-' + webhost,`

But I like to control this with the --html parameters So I can only archive anything under mydir and send it.

I tried the following:
```
    @pytest.fixture(scope='session')
    def reportname(request):
>       name_value = request.config.option.html
E       AttributeError: 'Namespace' object has no attribute 'html'
```

**Comment by fenchu** [comment]
I find self_contained_html, but not --html in request.config.option:
`reportname:['__class__', '__contains__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__slotnames__', '__str__', '__subclasshook__', '__weakref__', '_get_args', '_get_kwargs', 'assertmode', 'base_url', 'basetemp', 'cacheclear', 'cacheshow', 'capture', 'collect_in_virtualenv', 'collectonly', 'color', 'confcutdir', 'continue_on_collection_errors', 'css', 'debug', 'deselect', 'disable_warnings', 'doctest_continue_on_failure', 'doctest_ignore_import_errors', 'doctestglob', 'doctestmodules', 'doctestreport', 'durations', 'failedfirst', 'file_or_dir', 'fulltrace', 'help', 'htmlpath', 'ignore', 'ignore_glob', 'importmode', 'inifilename', 'junitprefix', 'keepduplicates', 'keyword', 'last_failed_no_failures', 'lf', 'log_cli_date_format', 'log_cli_format', 'log_cli_level', 'log_date_format', 'log_file', 'log_file_date_format', 'log_file_format', 'log_file_level', 'log_format', 'log_level', 'log_print', 'markers', 'markexpr', 'maxfail', 'metadata', 'newfirst', 'noconftest', 'override_ini', 'pastebin', 'plugins', 'pyargs', 'pythonwarnings', 'reportchars', 'resultlog', 'rootdir', 'runxfail', 'self_contained_html', 'setuponly', 'setupplan', 'setupshow', 'show_fixtures_per_test', 'showcapture', 'showfixtures', 'showlocals', 'stepwise', 'stepwise_skip', 'strict_markers', 'tbstyle', 'trace', 'traceconfig', 'usepdb', 'usepdb_cls', 'variables', 'verbose', 'verify_base_url', 'version', 'webhost', 'xmlpath']`

**Comment by fenchu** [comment]
I found it in htmlpath:
htmlpath=mydir/report.html

Would be nice if this was in the documentation :-)

**Comment by Harshithkumar** [comment]
@fenchu I am getting the same error while i am running pytest. 

=======================
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3 "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py" --target test_WTW.py::Test_WTW.test_cast_icon
Testing started at 1:30 PM ...
/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pycharm/_jb_pytest_runner.py:28: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if version.LooseVersion(pytest.__version__) >= version.LooseVersion("6.0"):
Launching pytest with arguments test_WTW.py::Test_WTW::test_cast_icon in /Users/hakumar/pythonProject/AppiumAndroid/tests

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1104, in getoption
INTERNALERROR>     val = getattr(self.option, name)
INTERNALERROR> AttributeError: 'Namespace' object has no attribute 'htmlpath'
INTERNALERROR> 
INTERNALERROR> During handling of the above exception, another exception occurred:
INTERNALERROR> 
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/main.py", line 202, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 773, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/appiumbase/plugins/pytest_plugin.py", line 242, in pytest_configure
INTERNALERROR>     ab_config.pytest_html_report = config.getoption("htmlpath")  # --html=FILE
INTERNALERROR>   File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/_pytest/config/__init__.py", line 1115, in getoption
INTERNALERROR>     raise ValueError("no option named %r" % (name,))
INTERNALERROR> ValueError: no option named 'htmlpath'

Process finished with exit code 3

Empty suite
==========================

**Comment by Harshithkumar** [comment]
Can anybody help me  ??!
