### ISSUE TITLE
Windows users unable to open test reports with assets created on Linux

### ISSUE THREAD

**Issue by christopheraranda** [pytest-dev/pytest-html#221]
I have functional tests that are executed in a CentOS based container. The logging for those tests is redirected to a text asset and appended as an extra in the HTML report.

After the tests are executed, the report and the assets are compressed to a ZIP file and are emailed out. Windows users that receive the report are unable to decompress the file.

Since the tests are in subdirectories, the nodeid contains forward slashes. As a result, directories are also created in the assets directory. I suspect that the forward slashes and colons in the nodeid are causing unintended consequences when creating the asset.

https://github.com/pytest-dev/pytest-html/blob/c9eadb0b76d5aaaecdb8fb45600bafd851d9ca27/pytest_html/plugin.py#L161

**Comment by BeyondEvil** [comment]
Thanks for this @christopheraranda !

I'm not sure this is solveable in code. 🤔 

But I do have two suggestions:

1. Have you tried using `--self-contained-html` flag?
2. Make sure when you're ZIPping the files, you're making the zip file portable (that as is, portable across different OSes).

If you have an idea or more info about the possibility of solving this in code - please share.

**Comment by christopheraranda** [comment]
@BeyondEvil unfortunately, using the --self-contained-html flag is not an option. My tests are generating a lot of logging, and the HTML report size is getting to close to 100MB in some cases. This is bringing the browser to its knees, so I needed to extract the logs to a text asset for each test case.

However, the fix for issue [#215](https://github.com/pytest-dev/pytest-html/issues/215) seems to have resolved the problem that I was having. The assets are being created without subdirectories and invalid file name characters.

Windows users were still having problems decompressing the zip file with the default extraction app, but switching to 7-Zip resolved the problem.

You can probably close this issue. Thanks for your help!

**Comment by BeyondEvil** [comment]
Great to hear everything was solved @christopheraranda !
