### ISSUE TITLE
Ability to add text above captured log output?

### ISSUE THREAD

**Issue by VorpalBlade** [pytest-dev/pytest-html#222]
Is it possible (or feasible to extend) to insert extra output above the test output. I would be interested in inserting the docstring of the test function here to provide details on the test.

Something like this quick mockup using the HTML inspector in Firefox:
![pytest_mockup](https://user-images.githubusercontent.com/3315306/61718675-bf0a4680-ad63-11e9-9796-5b9255c6ea2b.png)

**Comment by BeyondEvil** [comment]
Interesting. I'll try to investigate in the coming weeks.

**Comment by VorpalBlade** [comment]
Turns out I'm able to do this with pytest_html_results_table_html. Missed that before. My bad.
