### ISSUE TITLE
Deprecate compability with python 2.7 

### ISSUE THREAD

**Issue by RibeiroAna** [pytest-dev/pytest-html#228]
Hi there,

Recently I run something with Python 2.7 and got the following message: 

"DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support"

I think that by January 1st, we should drop support to Python 2.7 as well. What do you think?

@davehunt @BeyondEvil

**Comment by BeyondEvil** [comment]
Yes! Agreed @RibeiroAna.

I think we're going to do this across most plugins.

**Comment by hugovk** [comment]
Please see PR #230.
