### ISSUE TITLE
Opening report is slow when it contains long logs

### ISSUE THREAD

**Issue by Wramberg** [pytest-dev/pytest-html#239]
I have some test runs that generate a lot of log entries. When opening the report is seems my browser is spending a lot of time presenting all these entries which are immediately collapsed right after.

If I change the behavior to have everything collapsed by default I can open/render the html report much faster.

What I have tested is essentially the same as adding a "collapsed" class here https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/plugin.py#L140

I have no idea if this breaks other use-cases or if other changes are necessary. I also realize that everything related to the collapse functionality is currently in js. Regardless, if something could be done to generate everything collapsed and open the necessary stuff afterwards I believe performance would be a lot better.

Edit: I should mention I use self-contained reports.

**Comment by fpiccione** [comment]
@Wramberg maybe [this](https://stackoverflow.com/questions/57282301/send-html-report-with-row-collapsed) will work ?

**Comment by Wramberg** [comment]
@fpiccione Yes it will. But my issue is about having to make a manual hack.

**Comment by BeyondEvil** [comment]
Would this help: https://github.com/pytest-dev/pytest-html/pull/168 @Wramberg

**Comment by Wramberg** [comment]
@BeyondEvil I dont think so. It seems to change which rows are collapsed but not the fact that ALL rows as rendered as non-collapsed just to be collapsed later by javascript. If we instead rendered the passed rows collapsed the rendering would be a lot faster.

**Comment by BeyondEvil** [comment]
@Wramberg Ah, I see.

How would you like to see this accomplished? INI-file (pytest.ini etc) setting?

**Comment by Wramberg** [comment]
I imagine it can simply be changed permanently. I do not see this breaking anything since it would not change the final rendered page, just the way it is rendered - but perhaps I am missing something ?

Regardless a command line option or INI setting would be fine for me.

**Comment by BeyondEvil** [comment]
Even tho it wouldn't technically break something, I'm reluctant to change a behaviour going back multiple years.

Happy to add an INI setting however.

**Comment by Wramberg** [comment]
I understand. Whichever approach you prefer :+1:

**Comment by BeyondEvil** [comment]
Hey @Wramberg 

Would you mind perf-testing my PR?

**Comment by Wramberg** [comment]
@BeyondEvil Sure. I will check it out tomorrow.

**Comment by BeyondEvil** [comment]
I merged it. But please feel free to use master branch. Good to have a test before I do a release. @Wramberg

**Comment by Wramberg** [comment]
Alright will do

**Comment by Wramberg** [comment]
> Alright will do

@BeyondEvil see my reply on your PR #267.

**Comment by BeyondEvil** [comment]
> > Alright will do
> 
> @BeyondEvil see my reply on your PR #267.

Yes, thanks @Wramberg !

Fix in #268 

Please re-test if you have time. :)

**Comment by BeyondEvil** [comment]
Please test now @Wramberg 🙏

**Comment by Wramberg** [comment]
> Please test now @Wramberg 🙏

Sorry, time has been limited. According to a fast copy pasta test of the core functionality indicates that it work 👍
