### ISSUE TITLE
Is it possible to remove "No log output captured." report section in case when additiomal HTML has been used?

### ISSUE THREAD

**Issue by faleev** [pytest-dev/pytest-html#24]
I would like to have an ability to suppress log section in case if I'm using additional HTML in the report and log itself does not contains any information besides of "No log output captured."

(could you just remove [lines 143-145](https://github.com/davehunt/pytest-html/blob/master/pytest_html/plugin.py#L143-L145) and move [additional_html.append(log)](https://github.com/davehunt/pytest-html/blob/master/pytest_html/plugin.py#L146) inside the IF section in the plugin.py file)

**Comment by davehunt** [comment]
Could you explain in more detail what you are wanting to see? Perhaps you could mock something up and submit a screenshot? The 'No log output captured' is included to make it clear that there was nothing captured, rather than it being captured but for some reason not displayed on the report.

**Comment by davehunt** [comment]
With #43 the extra details can be collapsed (and are collapsed by default for passing tests). Please reopen with more details if this is not sufficient. Note that the feature will be in the upcoming release.
