### ISSUE TITLE
A dictionary item gets printed in the row when I try to add a url link to the report

### ISSUE THREAD

**Issue by altran-git** [pytest-dev/pytest-html#241]
Along with the actual URL link, the following gets printed in the row when I try to add a url link to the report:

{'name': 'URL', 'format': 'url', 'content': 'http://www.example.com', 'mime_type': None, 'extension': None}

Not sure why this is happening.

**Comment by BeyondEvil** [comment]
Can you show us your code @altran-git ?

**Comment by altran-git** [comment]
`from py.xml import html
import pytest

def pytest_html_results_table_row(report, cells):
    cells.insert(3, html.td(report.extra, class_="col-links"))

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    extra = getattr(report, 'extra', [])
    if report.when == 'call':
        # always add url to report
        extra.append(pytest_html.extras.url('http://www.example.com'))
        report.extra = extra
`

**Comment by BeyondEvil** [comment]
What versions are you on (python, pytest, pytest-html, pytest-selenium(?))? @altran-git

**Comment by altran-git** [comment]
python: 3.7
pytest: 5.0.1
pytest-html: 2.0.0

(not using selenium)

**Comment by BeyondEvil** [comment]
The problem is this:

```python
def pytest_html_results_table_row(report, cells):
    cells.insert(3, html.td(report.extra, class_="col-links"))
```

You're inserting the entire `report.extra`.

@altran-git

**Comment by altran-git** [comment]
ahh, thank you.
