### ISSUE TITLE
py.test dont run test-cases. I see SyntaxError: invalid syntax. I will show it on sreen below. 

### ISSUE THREAD

**Issue by JenyaKrixus** [pytest-dev/pytest-html#243]
Hello!

I have problem with running py.test on Pycharm. I open Terminal on Pycharm, and try to run my tests using py.test, but after it, i see exeption. There is my screen 
![Selection_999(045)](https://user-images.githubusercontent.com/56037537/65975754-c3479400-e477-11e9-914e-5233f27950b0.png)

I noticed this problem after installing "pip3 install pytest-html"
Can anybody help me? Because earlier everything was fine

Thank you!

**Comment by JenyaKrixus** [comment]
> pytest-html is python3.6+ only it appears and you're using python3.5

Thank you, Anthony Sottile ! But now, i can't even run py.test ...location of test file. Can it be the reason, that i have installed  pytest-html?

**Comment by asottile** [comment]
yes, you can always `pip uninstall pytest-html` to get back to the state before you installed it

**Comment by JenyaKrixus** [comment]
Thanks, i will install newest version of Python

**Comment by asottile** [comment]
cool, I don't think there's anything really actionable from the pytest-html side -- thanks for the issue!
