### ISSUE TITLE
Dictionaries in environment table a not sorted

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-html#245]
As in Python dictionaries are not (usually) sorted printing the environment gives random results, making much harder to read it and to compare it with previous runs.

Example: http://logs.rdoproject.org/52/23152/1/check/rdo-tox-molecule/6eb5f91/tox/reports.html

**Comment by BeyondEvil** [comment]
Fair point!

Feel free to contribute with a fix! 😄 

There's a couple of other issues with your name on them 😉

**Comment by ssbarnea** [comment]
@BeyondEvil Sad to dissapoint you but since you dropped support for py27 I lost my interest of contributing as most of our jobs are still on python27. Hopefully this may change next year, once I manage to migrate more jobs.

While I support dropping support for py27, pytest stuff is not one of the places to start because is used for testing, lots of people will continue to use it next year because they have LTS maintenance branches with CI/CD on them. When you cannot fix the versions you are using the incentive to contribute goes down rapidly.

**Comment by BeyondEvil** [comment]
@ssbarnea I see, that is disappointing indeed.

And I guess, it's our fault for not communicating properly, but we haven't dropped support for python 2.7 (at least not the way you think we have).

Read more here: https://docs.pytest.org/en/latest/py27-py34-deprecation.html
