### ISSUE TITLE
Getting ResourceWarning: unclosed file open(csspath)

### ISSUE THREAD

**Issue by wanam** [pytest-dev/pytest-html#246]
I'm getting bellow error while loading a custom css file:
ResourceWarning: unclosed file <_io.TextIOWrapper name='assets/style.css' mode='r' encoding='UTF-8'>open(csspath)

The bug is similar to https://github.com/pytest-dev/pytest/issues/4355

I'm wondering if [this code block](https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/plugin.py#L70-L71) is just a leftover, because I think the custom css file is loaded [here](https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/plugin.py#L345-L352).

**Comment by BeyondEvil** [comment]
Mind sharing some details about your environment? @wanam 

OS
python version
pytest-html version
any other versions you might thing are pertinent?

Also, could you provide a sample css-file that causes the error?

Thanks!

**Comment by wanam** [comment]
OS: Ubuntu 18.04.3 LTS
platform linux -- Python 3.7.2, pytest-5.1.2, py-1.7.0, pluggy-0.13.0
plugins: metadata-1.8.0, csv-2.0.1, html-2.0.0

```
venv/lib/python3.7/site-packages/pytest_html/plugin.py:71: ResourceWarning: unclosed file <_io.TextIOWrapper name='assets/style.css' mode='r' encoding='UTF-8'>
  open(csspath)
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

Concerning the asset, you can reproduce the issue with the default asset: https://github.com/pytest-dev/pytest-html/blob/master/pytest_html/resources/style.css

**Comment by janvanoverwalle** [comment]
Have had the same warning appear on Windows.

OS: Windows 10.0.18362 Build 18362
platform win32 -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.13.0
plugins: html-2.0.0, metadata-1.8.0

It does indeed seem, to me, like a redundant or leftover step in the `pytest_html\plugin.py` file as @wanam  mentioned.

**Comment by krzysztof-pawlik-gat** [comment]
I believe this will be solved when #235 is merged.

**Comment by BeyondEvil** [comment]
I'm terribly sorry, I thought I had merged #235 already!

@wanam Do you mind trying the patch (it's on `master` now) and see if that fixes your issue as well? 🙏

**Comment by wanam** [comment]
Tested the patch, and it seems fixed, thanks @krzysztof-pawlik-gat !
@BeyondEvil could you also check this one https://github.com/pytest-dev/pytest-html/pull/248 before releasing?

**Comment by janvanoverwalle** [comment]
Appears fixed from my end as well. Thanks!

**Comment by BeyondEvil** [comment]
Awesome! Thank you everyone! 🙏
