### ISSUE TITLE
text formatting in table cells

### ISSUE THREAD

**Issue by kyochujoho** [pytest-dev/pytest-html#252]
Hello, currently it does not appear possible to have pytest-html recognize, for example, carriage returns in strings fed to table cells. The use case I'm considering is inserting my docstrings into a test description cell:

`@pytest.mark.hookwrapper
def pytest_runtest_makereport(item, call):
    pytest_html = item.config.pluginmanager.getplugin('html')
    outcome = yield
    report = outcome.get_result()
    report.description = item.function.__doc__`

This is undesirable from a readability standpoint. Am I perhaps missing something or might there be a workaround?

**Comment by BeyondEvil** [comment]
Hi @kyochujoho 

This isn't really a plugin-thing, but more an html-thing. The solution is likely to provide a `style`-attribute to the `td`:

```python
cells.insert(2, html.td(report.description, style="white-space:pre-wrap; word-wrap:break-word"))
```
You can also provide your own (global) CSS styling using the `--css` flag.

Hope that helps!
