### ISSUE TITLE
 unrecognized arguments

### ISSUE THREAD

**Issue by ForAxel** [pytest-dev/pytest-html#253]
After I installed the 'pytest-html' by using 'pip install pytest-html'  and try to use it by inputing 
```
pytest ./case.py --html=record.html
```
I found it can't work as excepted with error:'unrecognized arguments: --html=record.html'
So I wanna know what can I do to solve this problem?

**Comment by BeyondEvil** [comment]
@ForAxel  Please see issue #146 

If that doesn't solve it for you, get back to us with some more information about your environment and if possible detailed steps to reproduce.

Thanks!

**Comment by ForAxel** [comment]
Thank you! I solved this problem by using
```
pip3 install -U pytest
```

**Comment by BeyondEvil** [comment]
Glad to hear it!
