### ISSUE TITLE
Option to enable report update after each tests

### ISSUE THREAD

**Issue by happz** [pytest-dev/pytest-html#254]
In my workflow, I'd appreciate an option which would let me ask `pytest-html` to save the report after each test. I'm using `pytest-xdist` to run multiple tests simultaneously, and it would be very helpful to get a fresh HTML page as soon as any test completes, it would allow us to start fixing issues without waiting for the long-running tests to catch up.

**Comment by BeyondEvil** [comment]
Interesting. Not sure if it's possible without a major refactor. But I'll investigate.

**Comment by BeyondEvil** [comment]
Like I suspected, this will require a major refactor and it would be a hard requirement to not break any of the existing functionality.

To update the report on every test would require that we open the file, write the intermediate result (in the right place!), and then close the file. This might be OK for a couple of tests, but would be very non-performant for a larger suite.

**Comment by happz** [comment]
I see. I was afraid you might say that, but thank's for checking.

In our case, each test may run several minutes, even an hour, therefore repeated open-write-close overhead wouldn't be an issue for us. I'll try to investigate the `HTMLReport` class and how to use it, I must find out how pytest-xdist processes communicate results back to where the report is generated. Maybe it's not even possible to get an update after each test, but for all tests at once when process ends.

**Comment by BeyondEvil** [comment]
Good luck!

**Comment by jamiebernardin** [comment]
@happz were you able to make any progress??  I have a similar use case.  thank you.
