### ISSUE TITLE
I see an IOerror  and OSError while running pytest with -css parameter along with html report

### ISSUE THREAD

**Issue by PravinAlhat** [pytest-dev/pytest-html#255]
I see below error while running pytest with -css parameter along with html report

$ pytest --html=API.html --css=highcontrast.css --css=accessible.css

INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/_pytest/main.py", line 192, in wrap_session
INTERNALERROR>     config._do_configure()
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/_pytest/config/__init__.py", line 726, in _do_configure
INTERNALERROR>     self.hook.pytest_configure.call_historic(kwargs=dict(config=self))
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pluggy/hooks.py", line 308, in call_historic
INTERNALERROR>     res = self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/Users/pravin.a/my-project/venv/lib/python3.8/site-packages/pytest_html/plugin.py", line 72, in pytest_configure
**INTERNALERROR>     raise IOError(f"No such file or directory: '{csspath}'")**
**INTERNALERROR> OSError: No such file or directory: 'highcontrast.css'**

![image](https://user-images.githubusercontent.com/38999712/72068520-3d0adb80-330b-11ea-8ded-4483e059ee22.png)

**Comment by BeyondEvil** [comment]
Sorry for taking so long to respond @PravinAlhat 

I need some more information from you:
- What OS and OS-version are you getting this on?
- What versions of python, pytest and the pytest-html plugin are you using?
- Is happening locally or on a CI environment (incl. VM/Docker)?

If possible, it would be great if you could provide a small reproducible test (in code) and also example css-files.

Thanks!

**Comment by PravinAlhat** [comment]
@BeyondEvil 
OS - MacOS Catalina
OS-version - 10.15.2
python version- Python 3.8.1
pytest version - pytest 5.3.1
pytest-html plugin - 2.0.1
This is happening locally.

No, I don't have files (highcontrast.css and accessible.css) in the root of the project. 

Please explain the usage of -css argument with --html in pytest. Actually I am not completely aware of how to use -css as an argument in pytest run.

**Comment by BeyondEvil** [comment]
> No, I don't have files (highcontrast.css and accessible.css) in the root of the project.

Well, that's the problem. You're telling the plugin to use these files for the styling, and since they don't exist you get `No such file or directory: 'highcontrast.css'`.

> Please explain the usage of -css argument with --html in pytest. Actually I am not completely aware of how to use -css as an argument in pytest run.

The `--css` flag is used if you **don't** want to use the default styling, but provide your own.

If you're happy with the default styling, you can just run using:

```bash
$ pytest --html=API.html
```
