### ISSUE TITLE
Need an ability to include "short test summary info" section into HTML report

### ISSUE THREAD

**Issue by AshotVantsyan** [pytest-dev/pytest-html#257]
Let have `test_1.py` test file with the following content:
```python
#!/usr/bin/env python3.7

import pytest

def test_1():
    pass

@pytest.mark.xfail(reason="Reason for expected failure")
def test_2():
    assert False

@pytest.mark.xfail(reason="Reason for unexpected failure")
def test_3():
    pass

@pytest.mark.skip(reason="Reason for skipped test case")
def test_4():
    pass

```

Running the test with `pytest test_1.py -rsxX --html test_results.html` command produces the following output:
```pytest
============================= test session starts ==============================
platform linux -- Python 3.7.3, pytest-5.2.2, py-1.8.0, pluggy-0.12.0
rootdir: $HOME
plugins: pylint-0.14.1, metadata-1.8.0, html-2.0.1
collected 4 items

test_1.py .xXs                                                           [100%]

--------- generated html file: file://$HOME/test_results.html ---------
=========================== short test summary info ============================
SKIPPED [1] test_1.py:16: Reason for skipped test case
XFAIL test_1.py::test_2
  Reason for expected failure
XPASS test_1.py::test_3 Reason for unexpected failure
============== 1 passed, 1 skipped, 1 xfailed, 1 xpassed in 0.40s ==============
```
And the following HTML report:
![test_results](https://user-images.githubusercontent.com/19218177/72154623-8c641100-33ca-11ea-811a-41e27e6e0336.png)

The generated HTML report is awesome, but there is a thing that I'm missing in the report - the reason for XPASS case is missing.

It would be nice to have an ability to include 'short test summary info' section information into the HTML report.

**Comment by AshotVantsyan** [comment]
Looks like no-one is going to look at this.

**Comment by BeyondEvil** [comment]
@AshotVantsyan https://github.com/pytest-dev/pytest-html#modifying-the-results-table

**Comment by AshotVantsyan** [comment]
> @AshotVantsyan https://github.com/pytest-dev/pytest-html#modifying-the-results-table

Thank you for the information. Despite this is not the thing that I've asked for but I'll take a look at this.

**Comment by freetomik** [comment]
> > @AshotVantsyan https://github.com/pytest-dev/pytest-html#modifying-the-results-table
> 
> Thank you for the information. Despite this is not the thing that I've asked for but I'll take a look at this.

Actually it can help to do desired action. This is working for me:
```
def pytest_html_results_table_header(cells):
    cells.insert(2, "<th>Fail reason</th>")

def pytest_html_results_table_row(report, cells):
    cells.insert(2, f"<td>{report.fail_reason}</td>")

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    report.fail_reason = call.excinfo.value if call.excinfo else None
```
