### ISSUE TITLE
Query: how to pass value to a new environment at runtime? 

### ISSUE THREAD

**Issue by p00j4** [pytest-dev/pytest-html#266]
https://github.com/pytest-dev/pytest-html#environment shows how to add a new env variable with a static value. I want to generate html with dynamic values which I get on the test run. something like in the setup stage. 
Use case: I want to inject variables like where did this test run, which DB, which env etc. 

**Here is snippet of my trials** 
testfile.py
```python
 def test_validator(self, request, payload):
    request.config._db_name = payload['db_name] #this doesn't work in configure plugin
    request.node._db_name = payload['db_name'] # this works in makereport plugin
```

**In conftest.py**
```python
pytest_runtest_makereport(item, call):
   print(getattr(item, 'db_name', "default"))  #this works and prints the db_name value passed 
```

but below doesn't work
```python
def pytest_configure(config):
    config._metadata['DB'] = getattr(config, '_db_name', 'default') #this always fail and prints default
```
I'm able to figure that, this is not supposed to work may be because **config** object doesn't have any info about the *item* object and also config is generated at the very beginning, till then the test_validator call is not reached. 

What can I change to make this work? I know i'm missing something really small here.

One way I see is to use options
``` config.getoption("--my_option_name")```
but that doesn't help if I want to build the variable value in the test/setup section

**Comment by BeyondEvil** [comment]
You can use the `pytest_metadata` fixture.

https://github.com/pytest-dev/pytest-metadata#accessing-metadata

Hope that helps!

**Comment by BeyondEvil** [comment]
```python
meta = getattr(item.config, '_metadata')
meta["DB"] = "some db name"
```

**Comment by p00j4** [comment]
worked like charm, thanks @BeyondEvil for the quick help
