### ISSUE TITLE
Can't freeze pytest with pytest-html plugin using PyInstaller

### ISSUE THREAD

**Issue by jackkrieger** [pytest-dev/pytest-html#272]
I'm trying to freeze my test code with pytest-html plugin using PyInstaller 3.6

My conftest.py contains HTML report customisation code:

```python
def pytest_html_results_summary(prefix, summary, postfix):
	dut_name = DEVICE
	prefix.extend([html.p(dut_name)])
```

There is a code in my test app to allow external plugins to be frozen:

```python
import pytest_html
import pytest_metadata

import pytest

result = pytest.main(['testdir'], plugins=[pytest_html, pytest_metadata])
```

When running the app I get
```
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_html_r
esults_summary' in plugin <module 'conftest' from '~\\conftest.py'>
```

**Comment by jmrgibson** [comment]
I just ran into this using [pyoxidizer](https://pyoxidizer.readthedocs.io/en/stable/), I think you want to use `pytest_html.plugin`, not just `pytest_html`

**Comment by jackkrieger** [comment]
Thanks! That works!
Also you need to add 'style.css' and 'main.js' as datas to be able to generate reports.

```python
extra_data = [
    ( '.\\resources\\style.css', '.\\pytest_html\\resources' ),
    ( '.\\resources\\main.js', '.\\pytest_html\\resources' ),
]

a = Analysis(...
             datas=extra_data,
   )
```
