### ISSUE TITLE
Hook pytest_html_report_title not available in tag 2.0.1

### ISSUE THREAD

**Issue by Maytrovato** [pytest-dev/pytest-html#279]
Hi guys, I just update the package in my repo but that hooks is still not available. Even tho is in the readme. Can you please update it? thanks.

It throws this message.

```
INTERNALERROR>     % (name, hookimpl.plugin),
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_html_report_title' in plugin

```

**Comment by christiansandberg** [comment]
It’s only in master. You need to look at the README for the released version:

https://pypi.org/project/pytest-html/

**Comment by BeyondEvil** [comment]
Thanks @christiansandberg 

This reminds me, I really need to do a release. 👍
