### ISSUE TITLE
2.1.0 release causing object has no attribute 'funcargs'

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-html#282]
Apparently the release of `pytest-html==2.1.0` broke our CI https://logserver.rdoproject.org/74/24774/67/check/rdo-tox-molecule/db3175d/job-output.txt

For the time being, I will pin-down: `pytest-html<2.1.0`

This bug is likely to affect any user of molecule, as we recommended using pytest-html to improve the reporting, but it is not a direct dependency of molecule tool itself, so we cannot really change module to workaround it.

**Comment by BeyondEvil** [comment]
Any idea how I can reproduce this locally? @ssbarnea 

Any idea what a fix could be? Apart from `hasattr` which seems more like a hack. 🤔

**Comment by BeyondEvil** [comment]
Ping @christiansandberg 😊

**Comment by christiansandberg** [comment]
Doh! I swear I saw that in the API but apparently not. 🙄 The list of extras could be global anyway since only one function is executed at a time. The list could be cleared on fixture setup. I can provide a pull request tonight.

**Comment by RonnyPfannschmidt** [comment]
as  per https://github.com/ansible-community/pytest-molecule/blob/master/pytest_molecule/__init__.py#L113 its a item, which doesn't have the attribute

**Comment by BeyondEvil** [comment]
> Doh! I swear I saw that in the API but apparently not. 🙄 The list of extras could be global anyway since only one function is executed at a time. The list could be cleared on fixture setup. I can provide a pull request tonight.

Thanks! 🙏

**Comment by christiansandberg** [comment]
@BeyondEvil I’ve made a pull request so you can make bugfix release.

**Comment by BeyondEvil** [comment]
Fix released in v2.1.1 @ssbarnea  👍
