### ISSUE TITLE
Jenkins doesn't execute the embedded script code of pytest-html reports

### ISSUE THREAD

**Issue by h-rueda** [pytest-dev/pytest-html#288]
It seems that Jenkins blocks the execution of the embedded script code of the pytest-html reports

All table rows are expanded by default and they don't have the click event attached to them.

**Comment by BeyondEvil** [comment]
I have extremely limited experience with Jenkins.

I don't think this has anything to do with the plugin or the report generated by it.

A quick search gave me [this](https://wiki.jenkins.io/display/JENKINS/Configuring+Content+Security+Policy#space-menu-link-content) but I can't say how, if at all, relevant it is.

I would probably start by reaching out the Jenkins community.

**Comment by h-rueda** [comment]
Actually is the Jenkins content-security-policy that blocks the JavaScript execution.

You can close this issue.

**Comment by BeyondEvil** [comment]
Glad I could help! 👍
