### ISSUE TITLE
Support a restricted version of the HTML report for security reasons

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-html#29]
When Jenkins addressed their [stored XSS vulnerability through workspace files and archived artifacts](https://wiki.jenkins-ci.org/display/SECURITY/Jenkins+Security+Advisory+2015-12-09), the HTML reports served became very limited. While it's possible to relax the security in Jenkins, it's not advisable. I wonder if we could degrade the HTML report gracefully for this case.

These are the [default rules](https://wiki.jenkins-ci.org/display/JENKINS/Configuring+Content+Security+Policy) now imposed by Jenkins:
* No JavaScript allowed at all
* No plugins (object/embed) allowed
* No inline CSS, or CSS from other sites allowed
* No images from other sites allowed
* No frames allowed
* No web fonts allowed
* No XHR/AJAX allowed

Without JavaScript, we lose support for [splitting the log and additional HTML onto a separate row](https://github.com/davehunt/pytest-html/blob/896fc16adbed412d8fd7fd77110096c092ec3124/pytest_html/resources/main.js#L163-L192), the [default sort order of test results](https://github.com/davehunt/pytest-html/blob/896fc16adbed412d8fd7fd77110096c092ec3124/pytest_html/resources/main.js#L126-L132), and the ability for users to change the sort order of the report. We should see if it's possible to take care of the first two in the generated HTML instead of relying on JavaScript.

All CSS is currently inline, so it may make sense for us to generate a CSS file alongside the HTML report. Currently the user specifies the path to the HTML file, which means we either have to make some assumptions about the available name for the CSS file. Perhaps instead of a file, we could support a directory, to which `index.html` and `style.css` can be written.

We also lose the [handling of images](https://github.com/davehunt/pytest-html/blob/896fc16adbed412d8fd7fd77110096c092ec3124/pytest_html/resources/main.js#L126-L132) that prevents large data URLs to be duplicated in the HTML. I believe that using data URLs for images should still work, so we should either find an optimal way to use them for both links and displayed images, or consider saving images as separate resources.

**Comment by The-Compiler** [comment]
I'd welcome having the default sort order in the generated HTML in any case - for me (with 3500 tests) it takes around 5 seconds until the full page is loaded and the results are sorted properly.

**Comment by davidedelvento** [comment]
Not sure if it's just me, but I like having CSS inline, so I have to shuffle around one file only. Maybe a configuration option to select either inline or separate file would be nice.

However that would change with the splitting the output in multiple htmls for #39 so maybe this single file to be shuffled convenience won't last anyway. I like the idea of selecting a directory

**Comment by davidedelvento** [comment]
@The-Compiler hopefully #39 and/or #33 will help with that part. However I agree, making javascript optional is more robust.

**Comment by davehunt** [comment]
> Not sure if it's just me, but I like having CSS inline, so I have to shuffle around one file only. Maybe a configuration option to select either inline or separate file would be nice.

A configuration file is an option. The original idea of using a single file was so that it's easy to move around, send via email, etc.

> However that would change with the splitting the output in multiple htmls for #39 so maybe this single file to be shuffled convenience won't last anyway.

Each HTML file could still be self-contained, so I think this is still relevant.

**Comment by RibeiroAna** [comment]
Just doing a Checklist to this enormous issue:
- [ ]  Splitting the log and additional HTML onto a separate row
- [ ]   Default sort order of test results
- [ ]   Write CSS and HTML in separated files
- [ ]    Handling of images

**Comment by RibeiroAna** [comment]
Just to make sure I understood, @davehunt, In "We also lose the handling of images that prevents large data URLs to be duplicated in the HTML", what do you exactly means by duplicated?

**Comment by davehunt** [comment]
> Just to make sure I understood, @davehunt, In "We also lose the handling of images that prevents large data URLs to be duplicated in the HTML", what do you exactly means by duplicated?

Currently the images are represented as base64 encoded data URLs, which are very large strings. We use this string for the `img` tag's `src` attribute, but also for the two link destinations. We're using JavaScript to pull the `src` of the image and use it as the `href` for the links, therefore avoiding repeating the long data URL.

**Comment by RonnyPfannschmidt** [comment]
wouldnt it make sense to write a folder and/or a web archive (that fancy .hta format, thats a zip of html + assets)

**Comment by davehunt** [comment]
@RonnyPfannschmidt the current plan is for @RibeiroAna to write images to a subfolder, and the `--standalone-html` option being introduced in #63 can then be used for anyone wanting to retain this feature for their HTML report. The web archive is an interesting idea to explore.
