### ISSUE TITLE
change htmlpath

### ISSUE THREAD

**Issue by broccoli** [pytest-dev/pytest-html#293]
The output says the report is at "generated html file: file:///project/report.html".  How do I change "project"?  It appears to come from `config.getoption("htmlpath")`.  How do I set that?  I've tried adding htmlpath value in pytest.ini.

**Comment by dasm** [comment]
@broccoli you can use `--html` to point to directory of choice: `pytest --html=~/report.html` will generate `report.html` file in your home directory.

**Comment by gnikonorov** [comment]
@broccoli I'm going to close this since you are able to use `--html` as @dasm suggested. Please reopen if your question wasn't properly answered.
