### ISSUE TITLE
development.rst link to tox is insecure

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-html#300]
Hi all, when I click the link to learn more about Tox in development.rst, Firefox flags the link as insecure. Perhaps it should redirect to https://tox.readthedocs.io/en/latest/#?

Location of link to Tox:
![Screen Shot 2020-05-21 at 9 34 34 PM](https://user-images.githubusercontent.com/13026015/82622259-52422180-9bab-11ea-8dcc-d0cf282f7013.png)

What Firefox shows when link to Tox is clicked:
![Screen Shot 2020-05-21 at 9 36 28 PM](https://user-images.githubusercontent.com/13026015/82622268-5a9a5c80-9bab-11ea-9706-39f400a763c3.png)

**Comment by BeyondEvil** [comment]
Fixed in #301
