### ISSUE TITLE
[pytest] render_collapsed = True  does not seem to work 

### ISSUE THREAD

**Issue by cauvery** [pytest-dev/pytest-html#304]
I tried the below from my tox.ini file and it does not seem to work  for html results to be collapsed

[pytest]
render_collapsed = True

Can someone please take a look at that feature if it is supposed to work from pytest.ini and/or tox.ini file.

Thanks,
Cauvery

**Comment by cauvery** [comment]
Hi can someone help on this

**Comment by cauvery** [comment]
This is working now. Thanks and closing this now

**Comment by priya24it** [comment]
How is this working ?

**Comment by Azee77** [comment]
can any one give details how did this work? What was the issue? For me it is not working, neither offline nor from jenkins artifacts
