### ISSUE TITLE
Export screenshots and log data into external sources

### ISSUE THREAD

**Issue by alexandermomot** [pytest-dev/pytest-html#32]
Hello folks!

Seems to be, screenshots for the report (as for selenium tests) stored right in the report file, encoded as base64 and then linked to the document. Also, driver log, browser log is stored same way. Is it possible to handle the screenshots data and send it to external source (file, or using external server by uploading as POST form-data), and return the link to the source instead of the source itself?

**Comment by davehunt** [comment]
This is related to #29 and I'd certainly welcome a patch that does this. The initial idea was that it can be more convenient for hosting/sharing if there's just a single file, however I see there are good reasons for using external resources. I can see two approaches here: either pytest-html could handle writing the files to disk and including relative links in the report, or like you suggest a URL for the resource could be passed directly into pytest-html.

**Comment by davehunt** [comment]
Images will be taken care of in #65 but I'm going to leave this open because it also mentions other types such as text and JSON.

**Comment by RibeiroAna** [comment]
I think this one can be the next issue I can work on, @davehunt , it will be easier since I have already done it to images

**Comment by davehunt** [comment]
@RibeiroAna sure, that makes sense to me. I'll add it to the 1.10.0 milestone.

**Comment by lambourn** [comment]
In my case, I do not have base64 encoded extra content when the report gets generated. Instead, my test logic already creates an external folder where screenshots are stored during test execution (so essentially no need to create assets at all as I do have everything in place)

Now I'l like to link to them (or use <img /> tag to "embed" them) just by using a file:// URL. 

Any ideas how I could get this into the html report?

**Comment by davehunt** [comment]
@lambourn you could append it as a link such as: `extra.append(pytest_html.extras.url('file://path/to/image', name='my image'))` or perhaps we could enhance `extras.image` to accept a path/URL as an alternative to a base64 encoded PNG. If you'd like this, please open a new issue.

**Comment by lambourn** [comment]
nice. Added this as https://github.com/pytest-dev/pytest-html/issues/77
