### ISSUE TITLE
proposal: combine ansi2html and non-ansi2html tox envs into one

### ISSUE THREAD

**Issue by ssbarnea** [pytest-dev/pytest-html#327]
We should be able to test pytest-html behavior in presence or absence of ansi2html without having two different tox environments.

By avoiding a new dimention in tox env matrix, we can simplify local and CI/CD testing, making much easier to maintain the tool. Absence of ansi2html cab easily be mocked.

Please add +/- to it and based on that I can file a PR, or not.

**Comment by BeyondEvil** [comment]
I'm interested to see a PR on this.
