### ISSUE TITLE
The Chinese code in the test report is confused

### ISSUE THREAD

**Issue by CerSU** [pytest-dev/pytest-html#339]
nodeid show Chinese code normal,but report to html is confused

**Comment by gnikonorov** [comment]
Hi @CerSU,

Thank you for opening this issue! Could you please elaborate more on what you are seeing in the report, along with a reproducer if possible

**Comment by CerSU** [comment]
I have Support Chinese for HTML  use case name display by customizing make Report ,Thanks!
