### ISSUE TITLE
[question] report tests in order as executed?

### ISSUE THREAD

**Issue by emdzejbi** [pytest-dev/pytest-html#341]
Failed steps are on top of the result table by default. Is there any way to tell pytest-html to report test results as in execution order?

**Comment by jahan01** [comment]
I have the same question - need to have report the in execution order.

**Comment by jahan01** [comment]
Workaround specified here worked for me https://github.com/pytest-dev/pytest-html/issues/103#issuecomment-282266577

```python
def pytest_html_results_table_header(cells):
    cells.insert(0, html.th("Finish Time", class_="sortable time initial-sort", col="time"))


def pytest_html_results_table_row(report, cells):
    cells.insert(0, html.td(datetime.utcnow(), class_="col-time"))
```
