### ISSUE TITLE
How can we modify the enviornment section AFTER the tests are completed

### ISSUE THREAD

**Issue by pranav165** [pytest-dev/pytest-html#373]
I have a requirement to report the average response time . This gets calculated after all the tests have run . Is it possible to show this as part of the test repot in the environment section ?

**Comment by gnikonorov** [comment]
@pranav165 this should be possible by doing something along the lines of:
```
def pytest_unconfigure(config):
    config._metadata["foo"] = "bar"
```

However, it's not working for me right now. I'm not sure why this is. I need to dig in and see. I'll update this issue as I progress

**Comment by gnikonorov** [comment]
Opened https://github.com/pytest-dev/pytest-metadata/issues/33 to see why this is.

**Comment by BeyondEvil** [comment]
Hi @pranav165!

Yes, you can update the `metadata` dictionary in the `pytest_sessionfinish` hook. By that time all tests have run and you should have access to all the response times so you can do the calculations.

```python
@pytest.hookimpl(tryfirst=True)
def pytest_sessionfinish(session, exitstatus):
    session.config._metadata["Average Response Times"] = calculate_avg_response(session)
```

Please close this issue if you're satisfied with the solution. 😊

**Comment by BeyondEvil** [comment]
Closing. Feel free to reopen if not satisfied.

**Comment by pranav165** [comment]
Thank you , it is working as expected
