### ISSUE TITLE
[PROPOSAL] Add issue templates

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-html#377]
I think we should add issue templates to this repository for a better user experience. [Issue templates](https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) would help users submit better bug reports/feature requests, which would in turn help the dev team have faster turnaround.

Pytest is [already using it](https://github.com/pytest-dev/pytest/issues/new/choose), and I think we could adopt a similar model.

Thoughts @ssbarnea / @BeyondEvil ?

**Comment by ssbarnea** [comment]
IMHO this project is small enough and with low activity to not need it but if you make a PR, I will review it. Closing to cleanup the backlog, not because this nice to have is not welcomed, just propose it.
