### ISSUE TITLE
Allow filtering report by test outcome

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-html#38]
It would be useful for users with large reports to be able to filter them by outcome. This will likely require JavaScript, but should degrade gracefully when this is not available. A suitable message should be displayed if no results match the filter applied. I imagine a list of outcomes with a checkbox, all checked by default, and unchecking a box would hide the associated results.

**Comment by RibeiroAna** [comment]
Hello, I'll start to write a design for this! Just to make sure that I understood what you mean, by "outcome" do you mean: seeing the report by the results, like seeing all the tests which passed, all which failed, etc.

**Comment by RibeiroAna** [comment]
Hi! I did a draft solution for that [here](https://github.com/RibeiroAna/pytest-html/commit/4c8051eef26da9ac4fe949b58ae4e6da47b48465), the idea is a search box, so users can search by anything (test outcome, test name, links or duration).

**Comment by davehunt** [comment]
I do like the idea of the user being able to filter by test name, but I'm not sure about having a single search box to include filtering the outcomes. Ideally the user would be able to display multiple outcomes, and I suspect the most common use will be to hide tests that passed from the results.

A few designs that come to mind are: 

- A list of checkboxes for each outcome, possibly replacing the existing summary section.
- Make the outcomes in the existing summary section clickable to toggle results with that outcome.
- Add a dropdown in the column header that allows filtering by one or more outcome.

I would suggest taking an existing HTML report and editing it to include this feature. Once you have something we're happy with it should then be relatively easy to add it to the plugin. I'd like to try to avoid using jQuery or other hosted scripts, but during the initial design/prototype phase I think this is fine.

It occurs to me that we should try to make it clear when a filter is applied, and perhaps include an obvious way to clear the filter in one click.

**Comment by davehunt** [comment]
This was fixed in https://github.com/pytest-dev/pytest-html/commit/fb4d5947fa0e264fffc0aacba6f4a854e97a7cd8
