### ISSUE TITLE
Control visibility of test results sections by query param

### ISSUE THREAD

**Issue by TheCorp** [pytest-dev/pytest-html#399]
Just like we can control collapsed test categories via query param (https://github.com/pytest-dev/pytest-html#display-options) would it also make sense to control whether test results sections are hidden or not (checkbox checked or not effectively) by query param? Something like:

`?checked=Passed,XFailed,Skipped`

The reason I am asking this is that it seems like this is nearly impossible to control before the page loads. We'd have to inject some JS that calls the "filter_tableI()" method for each section we want to check/uncheck or modify the <tbody> to have the "hidden" attribute before the page is generated.

I understand we can wholesale not render elements for any section using the output hooks (https://github.com/pytest-dev/pytest-html#modifying-the-results-table) but that would remove the ability for anyone to see the results if they were interested in seeing them. We have test output with hundreds of passed/skipped outputs usually and only a few failed ones. It would be nice if all of those were hidden by default but still viewable if the user wanted to view them. 

PR that did the original feature: https://github.com/pytest-dev/pytest-html/pull/168

**Comment by BeyondEvil** [comment]
Feel free to contribute a PR with a proposed solution! @TheCorp 😊 👍

**Comment by TheCorp** [comment]
Awesome. I just wanted to make sure the idea itself didn't sound stupid 😄

**Comment by BeyondEvil** [comment]
Definitely not! @TheCorp

**Comment by gnikonorov** [comment]
Hey @TheCorp I'm going to implement this. Let me know if you're already working on a solution. If not, I'll make a PR in the coming days

**Comment by TheCorp** [comment]
Oh wow @gnikonorov thank you! No I haven't had the chance to start on this yet so go for it. Really appreciate you taking this on.

**Comment by gnikonorov** [comment]
Of course @TheCorp. I'll have something up today or tomorrow
