### ISSUE TITLE
Report Table Configuration

### ISSUE THREAD

**Issue by michael-hart** [pytest-dev/pytest-html#40]
A feature request - would it be possible to add makereport hooks that allow the user to configure columns to add, or even hide? For instance, add a column with the docstring for a test description.

**Comment by michael-hart** [comment]
Possible solution to #34

**Comment by davehunt** [comment]
Fixed by adding hooks in bc2e8a35554df68113cd2ae911dc396cd32cfe93 available in v1.14.0.
