### ISSUE TITLE
[PROPOSAL] Use read the docs

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-html#401]
The readme is very long due to our documentation. 

I think it would be more convenient to have our documentation in [Read the Docs](https://readthedocs.org/) and have a link to it in the readme me in place of the documentation.

What do we  think @BeyondEvil and @ssbarnea ? If there are no objections, I'd like to set it up.

**Comment by ssbarnea** [comment]
go for it!

**Comment by BeyondEvil** [comment]
Indeed, go for it!

[pytest-selenium](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html) uses it as well if you need inspiration. @gnikonorov

**Comment by gnikonorov** [comment]
> Indeed, go for it!
> 
> 
> 
> [pytest-selenium](https://pytest-selenium.readthedocs.io/en/latest/user_guide.html) uses it as well if you need inspiration. @gnikonorov 

Thanks @BeyondEvil !

**Comment by gnikonorov** [comment]
Opened https://github.com/pytest-dev/pytest-html/pull/402 for this. I don't want to mark it as closing this issue, since I want to verify docs are published properly which requires the PR to merge first

**Comment by gnikonorov** [comment]
Confirming that autobuild on push to master works as expected

**Comment by ssbarnea** [comment]
Next time use magic comments "Fixes: #12345" inside PR description to auto-closed linked ticket.
