### ISSUE TITLE
Report arrows are missing off of head 

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-html#408]
Currently, there are no more arrows on the report headers. This doesn't happen off of the version in PyPI. We should fix this before release.

My current browser is Firefox v83.0 on MacOS

@jkowalleck, any idea why it may be gone? Could it be related to the recent SCSS changes?

Head version:
![Screen Shot 2020-12-11 at 12 29 35 AM](https://user-images.githubusercontent.com/13026015/101867089-626e1e00-3b48-11eb-871c-803164ed492e.png)

PyPI version:
![Screen Shot 2020-12-11 at 12 33 47 AM](https://user-images.githubusercontent.com/13026015/101867242-b2e57b80-3b48-11eb-89df-8917c7b237c4.png)

**Comment by BeyondEvil** [comment]
It was definitely the merge of https://github.com/pytest-dev/pytest-html/pull/393 that broke the report. Reverting to just before it brings the arrows back.

**Comment by jkowalleck** [comment]
looking into it.

**Comment by jkowalleck** [comment]
@gnikonorov  a bugfix is available: #409
