### ISSUE TITLE
Report title should reflect in report tab name

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-html#412]
Currently the tab of the report always has its text set to "Test Report" regardless of what the actual title of the report is. I propose to instead always have it set to the [report title](https://pytest-html.readthedocs.io/en/latest/user_guide.html#report-title).

If there are no objections @ssbarnea / @BeyondEvil I'll go ahead and make a PR

**Comment by BeyondEvil** [comment]
No objections from me @gnikonorov and I can't see a reason that @ssbarnea would object either, I think it's safe for you to go ahead and make a PR for it. 😊
