### ISSUE TITLE
CI pipeline is broken with error 'Error: IS_WINDOWS is not defined'

### ISSUE THREAD

**Issue by gnikonorov** [pytest-dev/pytest-html#429]
This seems to be related to https://github.com/actions/setup-python/issues/171. It's currently affecting the master build and PRs.

FYI @BeyondEvil / @ssbarnea

**Comment by gnikonorov** [comment]
https://github.com/pytest-dev/pytest-html/pull/430 rolls back to the last stable version so we can unbreak the CI pipeline

**Comment by hugovk** [comment]
Will be fixed by https://github.com/actions/setup-python/pull/172.

**Comment by gnikonorov** [comment]
Thanks for the news, @hugovk! Once the fix goes to master when will a new release be made?

**Comment by gnikonorov** [comment]
This could already be fixed as per https://github.com/actions/setup-python/issues/171#issuecomment-748114163. I'll confirm tonight (EST)

**Comment by hugovk** [comment]
Yep, looks fixed on my repo: https://github.com/hugovk/tinytext/actions/runs/428941900

**Comment by gnikonorov** [comment]
Can confirm it's fixed on PRs and master in this repo as well. Closing this issue then since no changes are needed
