### ISSUE TITLE
extra.svg(content: type?)

### ISSUE THREAD

**Issue by dramoz** [pytest-dev/pytest-html#440]
Hi, what should be the content type to pass when appending extra.svg()?

While doing:
`extra.append(extras.svg(svg))`

with
```python
svg = """<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 100 100">
  <circle cx="50" cy="50" r="43" fill="none" stroke="#000" stroke-width="9"/>
  <path d="M50,42c-6-9-20-9,-25,0c-2,5-2,11,0,16c5,9,19,9,25,0l-6-3c-2,5-9,5-11,0c-1-1-1-9,0-10c2-5,9-4,11,0z"/>
  <path d="M78,42c-6-9-20-9,-25,0c-2,5-2,11,0,16c5,9,19,9,25,0l-6-3c-2,5-9,5-11,0c-1-1-1-9,0-10c2-5,9-4,11,0z"/>
</svg>"""
```
https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/cc.svg

the generated .svg file in ./assets/xxxx.svg is not a valid svg file, but encoded (Looking at the code [src/pytest_html/result.py#L234](https://github.com/pytest-dev/pytest-html/blob/cc809864592638abe90c5c3a8bd1c03ab3f9970b/src/pytest_html/result.py#L234)
The report does not shows the proper SVG, however if I manually update the ./assets/xxx.svg with the proper SVG code, it shows the image as expected.

What should be the proper way to call extra.svg()?

Thanks,
Danilo.

**Comment by jkowalleck** [comment]
this worked for me:
```python
    image = """<?xml version="1.0"?>
<svg xmlns="http://www.w3.org/2000/svg" width="120" height="90">
    <rect x="0" y="0" width="100%" height="100%"
          fill="red" stroke-width="0" />
    <text x="50%" y="50%" fill="black"
          text-anchor="middle" alignment-baseline="central">
        EXAMPLE
    </text>
</svg>"""
    extra.append(
        extras.svg(
            b64encode(image.encode("ascii")).decode("ascii"), name="example_image"
        )
    )
```

**Comment by dramoz** [comment]
Thanks, it worked with:
`b64encode(svg.encode("utf-8")).decode("utf-8"), name="regex_svg"`
