### ISSUE TITLE
Multiple interpret information inside html report while used with pytest-xdist

### ISSUE THREAD

**Issue by wassupxP** [pytest-dev/pytest-html#462]
Hello,
I encountered bug or weird behaviour after bump of pytest and pytest-html. There is unwanted output, whichis not dependent on number of cores but is added per each phase of test. I dind´t find yet any workaround so this extra output is included in every testcase log.

List of plugins:
pytest | 6.0.1
pytest-cov | 2.10.1 
pytest-forked | 1.3.0
pytest-html | 3.1.1
pytest-metadata | 1.11.0 
pytest-xdist | 2.1.0 

Reproduction steps:
1. Create some dummy test.
2. Run pytest with xdist - something like: python -m pytest -n5 -v --self-contained-html --html=D://tmp//test_html//report.html

Expected results:
Nothing or max one lane of these outputs (not 4 same copies).

Actual results:
[gw0] win32 -- Python 3.6.6 PATH_TO_INTERPRET
[gw0] win32 -- Python 3.6.6 PATH_TO_INTERPRET[gw0] win32 -- Python 3.6.6 PATH_TO_INTERPRET[gw0] win32 -- Python 3.6.6 PATH_TO_INTERPRET

**Comment by wassupxP** [comment]
@gnikonorov May I ask what is the intention behind https://github.com/pytest-dev/pytest-html/blob/5e4950b6f47479eb3ce90999474b93c473e5aa9c/src/pytest_html/html_report.py#L287 this lane? If there is something that I don´t see. This is what creates problem and adds interpret info for each phase of test (2nd lane in my actual results) and I am not sure if this is intentional and there is some use case which I just don´t see.  
Thanks a lot for answer :)

**Comment by ugomancz** [comment]
I encountered this issue as well, any info? @gnikonorov

**Comment by BeyondEvil** [comment]
> I encountered this issue as well, any info? @gnikonorov

What version are you using?
