### ISSUE TITLE
Pytest-html generates html report even if no tests were run with VSCode

### ISSUE THREAD

**Issue by davidcasarez** [pytest-dev/pytest-html#510]
I am using VSCode and each time the test explorer runs a discovery/collects tests, a report.html file is generated even if no tests were run. I currently have my framework set up to create folders for each run with a report.html similar to the structure below. I am procedurally setting the the htmlpath in pytest_configure for pytest-html.

    /runs
    ..../2022-04-08-10-25-00
    ......../tests
    ............/name_of_test
    ................/logs
    ................/screenshots
    ................/captures
    ................/downloads
    ........report.html

Except I am getting the below structure when VSCode discovers tests and no tests are run.

    /runs
    ..../2022-04-08-10-25-00
    ........report.html
    ..../2022-04-08-10-26-00
    ........report.html

Here is my pytest_configure method for setting html path procedurally:

    @pytest.hookimpl(tryfirst=True)
    def pytest_configure(config):
      if "session_date" not in config.stash:
        config.stash["session_date"] = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    
      [...]
    
      run_path = config.rootpath.joinpath("runs", config.stash["session_date"])
      run_path.mkdir(parents=True, exist_ok=True)
      config.stash["run_path"] = run_path
    
      config.option.htmlpath = str(run_path / "report.html")

Any way to prevent html report generation if no tests are run?

**Comment by BeyondEvil** [comment]
I think this is an edge case we haven't considered, or it's a regression.

At the same time, I'm not sure what the expected behaviour should be. No report when zero tests or an "empty" report. 🤔

**Comment by BeyondEvil** [comment]
Can you repro it outside of VSCode?

**Comment by davidcasarez** [comment]
> Can you repro it outside of VSCode?

It works as intended when ran outside of VSCode. I was using VSCode in order to leverage the test explorer to select tests versus using the command line to run them. VSCode is somehow faux running the tests without actually running the tests when running test discovery and thus triggering the pytest_configure method.

**Comment by BeyondEvil** [comment]
Thanks!

So what do you think makes the most sense for the default behaviour? @davidcasarez

**Comment by davidcasarez** [comment]
@BeyondEvil 

I would think the default behaviour should be:
If no tests were run, then don't generate a report. 

Not sure if there is a way to determine this. I tried looking into this and possibly leveraging the pytest_sessionfinish hook to determine if tests were run and intercepting the _generate_report method.

**Comment by davidcasarez** [comment]
@BeyondEvil 

I solved it by updating my pytest_configure to check if collectonly is set to true and if it is then setting htmlpath to None:

    @pytest.hookimpl(tryfirst=True)
    def pytest_configure(config):
      if "session_date" not in config.stash:
        config.stash["session_date"] = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")
    
      [...]
    
      if config.option.collectonly == True:
        config.option.htmlpath = None
        
      else:
    
        [...]
    
        # Set run path
        run_path = config.rootpath.joinpath("runs", config.stash["session_date"])
        run_path.mkdir(parents=True, exist_ok=True)
        config.stash["run_path"] = run_path
    
        config.option.htmlpath = str(run_path / "report.html")
