### ISSUE TITLE
How can I modify the summary with test results after testing has finished?

### ISSUE THREAD

**Issue by nck974** [pytest-dev/pytest-html#533]
I have been able to modify the summary with the following snippet from another issue:
```python
def pytest_html_results_summary(prefix, summary, postfix):
    prefix.extend([
        html.button("Click me", onclick="myFunction()"),
        html.p(id="demo"),
        html.script(raw("""
        function myFunction() {
            document.getElementById('demo').innerHTML = 'Hello World';
        }""")),
    ])
```
And I am also able to gather the results after the session finishes with:

```python
def pytest_sessionstart(session):
    """
    This hook is called at the beginning and creates a placeholder to store all the results of the
    session
    """
    session.results = dict()

@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item):
    """
    Write the results of each test in the session
    """
    outcome = yield

    report = outcome.get_result()
    if report.when == "call":

        # Save result for later processing in pytest_sessionfinish hook
        item.session.results[item] = report

@pytest.hookimpl(tryfirst=True)
def pytest_sessionfinish(session, exitstatus):
    """
    This hook runs after all tests are done
    """
    print()
    print('run status code:', exitstatus)
    passed_amount = sum(1 for result in session.results.values() if result.passed)
    failed_amount = sum(1 for result in session.results.values() if result.failed)
    print(f'there are {passed_amount} passed and {failed_amount} failed tests')
    # TODO: Writing this in a file with a link
```
My problem is that I can not make a connection to write what I have in session finish with what I have in the summary. The summary hook seems to don't have have access to anyinformation of the session.

Furthermore, after making some prints, it seems the summary is generated before executing the `pytest_sessionfinish`.

Is there a work around to make my own summary additions after finishing the test?

**Comment by BeyondEvil** [comment]
Not sure what the correct solution is.

But let me label this `next-gen`, and once we've figured out how to deal with the hooks that modify the report - we can look at this use case.

**Comment by BeyondEvil** [comment]
Please try 4.0.0rc0 to see if this still is an issue.

**Comment by nck974** [comment]
I'm not sure if this is an issue.  As I commented before I used that hacky solution of writing over the HTML, if a hook can be implemented to be able to what is described in the title would be nice. Otherwise I do not have the need right now to change it.

**Comment by BeyondEvil** [comment]
> I'm not sure if this is an issue. As I commented before I used that hacky solution of writing over the HTML, if a hook can be implemented to be able to what is described in the title would be nice. Otherwise I do not have the need right now to change it.

Not 100% sure I understand the problem.

But here's what the current (4.0.0rc0) implementation looks like:

```python
    @pytest.hookimpl(trylast=True)
    def pytest_sessionfinish(self, session):
        session.config.hook.pytest_html_results_summary(
            prefix=self._report.data["additionalSummary"]["prefix"],
            summary=self._report.data["additionalSummary"]["summary"],
            postfix=self._report.data["additionalSummary"]["postfix"],
        )
        self._report.data["runningState"] = "Finished"
        self._generate_report()
```

Would changing that to something like:

```python
    @pytest.hookimpl(trylast=True)
    def pytest_sessionfinish(self, session):
        session.config.hook.pytest_html_results_summary(
            prefix=self._report.data["additionalSummary"]["prefix"],
            summary=self._report.data["additionalSummary"]["summary"],
            postfix=self._report.data["additionalSummary"]["postfix"],
        )
        self._report.data["runningState"] = "Finished"
        self._generate_report()

**Comment by nck974** [comment]
At first glance I think it would enough. Unfortunately I won't have time to verify that any time soon, as I do not have quick access right now to the code where I was using that.

**Comment by BeyondEvil** [comment]
> At first glance I think it would enough. Unfortunately I won't have time to verify that any time soon, as I do not have quick access right now to the code where I was using that.

No worries. There's no afaict downside to adding the session info to the hook. I'll make it part of the next RC so you can test whenever you have time.

**Comment by nahuelmariani** [comment]
Hi @BeyondEvil! I'm facing the same situation described by @nck974. I would love to have the session as parameter of the pytest_html_results_summary hook in the new RC.
Thank you so much!

**Comment by BeyondEvil** [comment]
Thanks for reminding me! I’ll see if I can get it added today and release a new RC you can try.
