### ISSUE TITLE
Unescape logs section to display custom html logs

### ISSUE THREAD

**Issue by MartykQ** [pytest-dev/pytest-html#545]
Is there a way to disable html escaping to display custom logs directly from `logging.info()`

Example:

```python

def test_abcd(f1):
    assert 3 > 1, "always passes"
    logging.info("<div>Custom div text</div>")   
```

it is displayed as a raw text in the html report, but I would like to have it displayed as a separate div

**Comment by BeyondEvil** [comment]
Maybe this https://pytest-html.readthedocs.io/en/latest/user_guide.html#extra-content

or this https://pytest-html.readthedocs.io/en/latest/user_guide.html#modifying-the-results-table

**Comment by BeyondEvil** [comment]
Closing this for lack of interaction. Feel free to re-open.
