### ISSUE TITLE
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]

### ISSUE THREAD

**Issue by mrhouzlane** [pytest-dev/pytest-html#547]
I have install pytest 

I am in a virtual environment using pipenv sync , pipenv run shell.

Environment : `macOs`
pytest v : `pytest 7.1.3`

I have this error when running pytest: 

```
ERROR: usage: pytest [options] [file_or_dir] [file_or_dir] [...]
pytest: error: unrecognized arguments: --cov --cov-report term-missing
  inifile: /Users/mehdirhouzlane/aleph-client/setup.cfg
  rootdir: /Users/mehdirhouzlane/aleph-client
```

**Comment by RonnyPfannschmidt** [comment]
Looks like options for Pytest-cov got added in adopts but Pytest-cov is not installed

**Comment by mrhouzlane** [comment]
Fixed.
