### ISSUE TITLE
[help] just curious how `--self-contained-html` option works?

### ISSUE THREAD

**Issue by LeiYangGH** [pytest-dev/pytest-html#548]
I searched the whole src folder and only see single [occurance](https://github.com/pytest-dev/pytest-html/blob/master/src/pytest_html/plugin.py#L29) and cannot find anywhere to reference this option.
can anyone help me understand how this option work?

**Comment by BeyondEvil** [comment]
Start here: https://pytest-html.readthedocs.io/en/latest/user_guide.html#creating-a-self-contained-report

**Comment by BeyondEvil** [comment]
And then here: https://github.com/pytest-dev/pytest-html/search?q=contained

**Comment by BeyondEvil** [comment]
Feel free to reopen if you need more help.

**Comment by LeiYangGH** [comment]
thanks!
