### ISSUE TITLE
Is there a way to reduce html size without removing logs?

### ISSUE THREAD

**Issue by AZ-201** [pytest-dev/pytest-html#552]
I got a lot of test.  Actually the report size is about 120M.  
![thumbnail_a8b2d61f3253b4469a80e55d708f02ac](https://user-images.githubusercontent.com/47150065/196147135-fd9e1b24-c7ea-4d74-affc-20583c9c662c.png)  
```
total 119M
-rw-r--r-- 1 xxx xxx 119M 8月   9 10:48 report_master_2022-08-09_103045.html
```
The browser won't load it normally, and crashed sometimes. I can't checkout the boxes and fold the results.  
Is there a way to reduce the size of it?  
The logs are necessary for debug.

**Comment by AZ-201** [comment]
I tried gzip the report html, got only 3.5M.  
Maybe there is a lot of room in optimization.
```
total 122M
-rw-r--r-- 1  119M 8月   9 10:48 report_master_2022-08-09_103045.html
-rw-r--r-- 1  3.5M 8月   9 10:48 report_master_2022-08-09_103045.html.gz
```

**Comment by BeyondEvil** [comment]
There are a couple of optimizations we're looking at.

One of them is to paginate and lazy load assets.

We welcome other suggestions!

**Comment by AZ-201** [comment]
> One of them is to paginate and lazy load assets.

Glad to hear that. Looking forward to it.

**Comment by AZ-201** [comment]
I checked the docs and found a visibility filter feature unreleased two years ago. May be considering add that feature in the next release is a good idea

**Comment by AZ-201** [comment]
I tried that feature mentioned before. It works, though loading still takes a lot of time.  
It has not been released yet. You can simply replace `main.js` to get it work.

**Comment by BeyondEvil** [comment]
> I checked the docs and found a visibility filter feature unreleased two years ago. Maybe considering add that feature in the next release is a good idea

Yep, it's already added. So are a couple of other filters that might help with loading.
