### ISSUE TITLE
Missing Dependency "py.xml" with pytest 7.2.0

### ISSUE THREAD

**Issue by smartEBL** [pytest-dev/pytest-html#553]
With latest pytest 7.2.0 we get a
`ModuleNotFoundError: No module named 'py.xml'; 'py' is not a package`

The py package dependency was removed here: https://github.com/pytest-dev/pytest/commit/19dda7c9bdc8ef71c792e0f77a9595bfad8d9248

This could be fixed by specifying the dependency in the pytest-html package itself.

**Comment by mielune** [comment]
Same for me.

**Comment by PeterStolz** [comment]
#554

**Comment by smartEBL** [comment]
https://github.com/pytest-dev/pytest-html/pull/555

**Comment by vgonisanz** [comment]
I have the same problem after updating pytest 6.X to pytest 7.X, are someone planning to release a new version of the plugin?

**Comment by DaffaPintu** [comment]
same for me

**Comment by PeterStolz** [comment]
Thanks for merging and releasing this quickly :100:
