### ISSUE TITLE
Release 3.2.0 is missing as release in your repo

### ISSUE THREAD

**Issue by WSADEERLBB** [pytest-dev/pytest-html#565]
Hi. The latest release as shown in Github is 3.1.1 dating back to July. There is only a tag 3.2.0. However it seems you published it already to PyPi and the changelog also shows 2022-10-25 as release date for the 3.2.0. Please make it a real release in Github as well.

**Comment by BeyondEvil** [comment]
Should be fixed now. Thanks for reporting!
