### ISSUE TITLE
when time < 10ms, the duration will be 0

### ISSUE THREAD

**Issue by WangFengtu1996** [pytest-dev/pytest-html#566]
* The duration_formatter is set `%M:%S.%f`
```
@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    '''data from the output of pytest gets processed here
     and are passed to pytest_html_results_table_row'''
    outcome = yield
    # this is the output that is seen end of test case
    report = outcome.get_result()
    setattr(report, "duration_formatter", "%M:%S.%f")
```
* got the duration will be zero.
![image](https://user-images.githubusercontent.com/21277368/201329525-e829e94b-e1af-427c-bb81-be7fd81602cb.png)

* This may not be bug. would someone give me some guide to show more detail time?
* Thanks for your time.

**Comment by BeyondEvil** [comment]
I think it depends on what we get from pytest.

I'll have a look, but I don't think you can get a better resolution on v3. But I'll see what the possibilities are for v4 (next-gen).

**Comment by BeyondEvil** [comment]
Having spent almost 2 hours looking at both the old and new duration formatting - I'm **VERY** tempted to remove this functionality all together.

Replace it with something that is not configurable, but "smarter":

"10 ms"

"34 sec"

"6:13 min"

"1:45:26 hrs"

Do you have a use-case where the formatting matters, apart from not showing 0 for a <10ms test?

**Comment by TUT-jiayou** [comment]
Hi，I&nbsp;just&nbsp;test&nbsp;the&nbsp;same&nbsp;case&nbsp;by&nbsp;adding&nbsp;sleep&nbsp;10ms&nbsp;then&nbsp;I&nbsp;get&nbsp;number&nbsp;00:00.01.&nbsp;I&nbsp;add&nbsp;sleep&nbsp;1s,&nbsp;then&nbsp;get&nbsp;00:01.00.&nbsp;

---Original---
From: &quot;Jim ***@***.***&gt;
Date: 2022/11/11 22:10:21
To: ***@***.***&gt;;
Cc: &quot;Fengtu ***@***.******@***.***&gt;;
Subject: Re: [pytest-dev/pytest-html] when time < 10ms, the duration will be 0(Issue #566)




 
Having spent almost 2 hours looking at both the old and new duration formatting - I'm VERY tempted to remove this functionality all together.
 
Replace it with something that is not configurable, but "smarter":
 
"10 ms"
 
"34 sec"
 
"6:13 min"
 
"1:45:26 hrs"
 
Do you have a use-case where the formatting matters, apart from not showing 0 for a <10ms test?
 
&mdash;

**Comment by TUT-jiayou** [comment]
* I just test same case by add sleep 10ms in test function. Then the number 00:00:01  is show in the html report.
* About `Do you have a use-case where the formatting matters, apart from not showing 0 for a <10ms test?` , I can get it.

**Comment by TUT-jiayou** [comment]
@BeyondEvil 
Hi, 
* I find the code that just get first two character strings in the duration millisecond.
https://github.com/pytest-dev/pytest-html/blob/a867776a403d007dfca7e22650fd8241bfabe0d1/src/pytest_html/result.py#L146-L175
* If I get all the string bits, can I submit the time precision ?
* About keep a precision of 2 for legacy reasons, how to understand it?

**Comment by TUT-jiayou** [comment]
Hi， @BeyondEvil 
* The issue https://github.com/pytest-dev/pytest/issues/10500 is open in pytest project. The container thinks that the duration is calculated rightly using `time.perf_counter()`
* I also test the python function  named `time.perf_counter()`,, It can get more detail time.
```
from time import perf_counter
import time
import logging
logging.basicConfig(format = '%(asctime)s - %(name)s - %(levelname)s - %(message)s-%(funcName)s',level=logging.DEBUG)


if __name__ == "__main__":
    start = perf_counter()
    time.sleep(0.001)
    end = perf_counter()
    duration = end - start
    logging.info(duration)
```
* result 
```
2022-11-16 09:55:51,563 - root - INFO - 0.0010866820812225342-<module>
```

**Comment by TUT-jiayou** [comment]
I open the PR https://github.com/pytest-dev/pytest-html/pull/568

**Comment by BeyondEvil** [comment]
Please test 4.0.0rc0
