### ISSUE TITLE
Support for pytest-benchmark

### ISSUE THREAD

**Issue by nirupbbnk** [pytest-dev/pytest-html#574]
(Feature request)
Hi Team,

Is it possible to give support for pytest-benchmark(https://pypi.org/project/pytest-benchmark/)

Thanks

**Comment by BeyondEvil** [comment]
You should be able to add it already using the available hooks: https://pytest-html.readthedocs.io/en/latest/api_reference.html

**Comment by BeyondEvil** [comment]
Closing this for lack of interaction. Feel free to re-open.
