### ISSUE TITLE
Cyrillic in Captured stdout call is corrupted

### ISSUE THREAD

**Issue by teverus** [pytest-dev/pytest-html#580]
Hi, everyone! Thank your for a wonderful way to print out reports! :)

I just have a quick question... In my tests I `print()` some info and capture it via `--show-capture=all` so that it would appear in the report.

However, it seems that Cyrillic letters cannot be printed out properly in the report, but I really need them there... is there a way to fix that?

I would appreciate any help :)

![2023_01_15__08_25_44](https://user-images.githubusercontent.com/62369371/212525674-f8e81d9a-7344-4a63-bb2e-b2df0dacda09.png)

**Comment by teverus** [comment]
@jfthuong offered a solution [HERE](https://github.com/pytest-dev/pytest-html/issues/559#issuecomment-1305181693) and it works! :) However, I wonder if there are alternative views on this problem?

**Comment by jfthuong** [comment]
@teverus  the fix I propose should work indeed
