### ISSUE TITLE
Add the ability to collapse Environment section using a Hide/Unhide

### ISSUE THREAD

**Issue by arindam31** [pytest-dev/pytest-html#622]
In some projects, the environment variable list is just too long. Takes a bit of a scroll to reach the test details.

**There can two solutions:**

1. Add a simple button

![114417843-3f18b580-9bb2-11eb-8edb-5d338e484345-2](https://user-images.githubusercontent.com/1822282/229665846-664df2c7-2477-4ef5-badd-4626ebd390da.jpg)

The JS will be also simple:

```
function hideEnvironment() {
  var x = document.getElementById("environment"); // 
  var buttonName = document.getElementById("environHideUnhide");
  if (x.style.display === "none") {
    x.style.display = "block";
    buttonName.innerText = 'Hide';
  } else {
    x.style.display = "none";
    buttonName.innerText = 'UnHide';
  }
}
```

2. Add the ability to add JS and HTML tags anywhere with a hook. May be based on IDs.

**Comment by BeyondEvil** [comment]
Maybe a query param to hide it by default would be good too?

**Comment by BeyondEvil** [comment]
For 2, I've been pondering the idea of allowing users to pass in their own Jinja2 and app.js. Basically only using the plugin as a pure backend.

Need to think some more about this.

**Comment by BeyondEvil** [comment]
Would you remind reviewing #638 @arindam31 ?

**Comment by BeyondEvil** [comment]
> Just curious - did there end up being a way to hide it by default via a config option, or just the mentioned options with custom templates?

Currently, the only way of hiding it is clicking the ”button”.
