### ISSUE TITLE
Question: Generate report with comparison of 2 runs

### ISSUE THREAD

**Issue by adydychk** [pytest-dev/pytest-html#652]
Hi all,
How can I generate report from two runs using pytest-html? I want to compare results of two runs. Maybe can it be done with another pytest plugin?

Thanks in advance.

**Comment by BeyondEvil** [comment]
As for generating two reports from two different runs, you can just name the reports differently

`--html=report1.html`

`--html=report2.html`


As for comparing them, I don't know if there's such a tool/plugin.

**Comment by BeyondEvil** [comment]
In the latest version (`4.0.0rc4`) the report now contains a json datablob with all test data. So should be fairly easy to extract what you need to compare.

There's also https://pypi.org/project/pytest-reportlog/

**Comment by adydychk** [comment]
@BeyondEvil thank you
