### ISSUE TITLE
extras in documnet should be changed to extra

### ISSUE THREAD

**Issue by LeiYangGH** [pytest-dev/pytest-html#662]
such as https://pytest-html.readthedocs.io/en/latest/user_guide.html#extra-content

**Comment by BeyondEvil** [comment]
This has been done for v4. (you can get `4.0.0rc4`) today.

**Comment by LeiYangGH** [comment]
thanks! may i ask a question here, i tried extra feature, but seems url, json and text are encoded as base64 by default, and get empty page when i click. is this behaviour by default? i cannot find any documents on this topic.

**Comment by LeiYangGH** [comment]
thanks!
