### ISSUE TITLE
extras to place in specific column

### ISSUE THREAD

**Issue by LeiYangGH** [pytest-dev/pytest-html#664]
I've read the documents but feel vague about extra's displaying. there's no images for those in docs.
When i test, i summarize current behaviour when adding text or json:
1. if no extra column added, a column called links will be automatically added, to hold the extra buttons.
2. sometimes if there's one column added, the last column will be used to hold extra buttons, but not always the case.
3. if add html, it is added to the area when single case is expanded
My question:
how to place the extra information into specified column? for example, the Duration column?
or just beside the html area?

**Comment by BeyondEvil** [comment]
> how to place the extra information into specified column? for example, the Duration column?

You can't place it in the default columns.

> just beside the html area?

What's the use case? What are you trying to achieve?

**Comment by LeiYangGH** [comment]
> > how to place the extra information into specified column? for example, the Duration column?
> 
> You can't place it in the default columns.
> 
> > just beside the html area?
> 
> What's the use case? What are you trying to achieve?

no specific purpose. I'm just thinking of all of the possibilities without document for the expected behaviour.

**Comment by LeiYangGH** [comment]
anyway, i think documents could be enhanced to demonstrate the _standard_ format.
