### ISSUE TITLE
Do not display reruns in summary when the plugin is not in use

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-html#67]
We should not include the 'reruns' in the report summary when the pytest-rerunfailures plugin is not registered.

**Comment by RibeiroAna** [comment]
by not in use, do you mean no reruns or the plugin is not installed? If you mean when the plugin is not installed, I could have something like "hasarg(rerun)", but how we could test it?

**Comment by davehunt** [comment]
I was thinking installed and registered. We should be able to use [config.pluginmanager.hasplugin](http://docs.pytest.org/en/latest/writing_plugins.html?highlight=pluginmanager#_pytest.config.PytestPluginManager.hasplugin) for this. For testing, you could try passing `-p no:rerunfailures` in the arguments.

**Comment by RibeiroAna** [comment]
What do you mean by registered? Do you mean when it is passed as parameter such as --rerun=2 or something like that? Because even when we don't pass anything it returns false
