### ISSUE TITLE
How to add additional column in pytest-html-reporter

### ISSUE THREAD

**Issue by yanetsi** [pytest-dev/pytest-html#687]
Hi, 
I am using **Pytest-HTML-Reporter 0.2.9**, it seems very good to me.
But I need to add a column in the report, and that column shows the link or id of my issue created in Gitlab and I don't know how to do it.
Can anybody help me?

I need to add a column here:  
![image](https://github.com/pytest-dev/pytest-html/assets/42178726/bee28576-645e-44b7-a705-07a057caf6f3)

**Comment by BeyondEvil** [comment]
Wrong plugin. You want: https://github.com/prashanth-sams/pytest-html-reporter
