### ISSUE TITLE
Display test_case docstring as description in test report

### ISSUE THREAD

**Issue by kiran-vemuri** [pytest-dev/pytest-html#69]
Along with result, test, duration and links, it'd be great if we have a test_case description field in the test report. The values for the description field will be the docstring for that specific test case.

If we already have a way to achieve this, please let me know.

**Comment by RibeiroAna** [comment]
I think it is related to the issue #40

**Comment by davehunt** [comment]
This looks like a duplicate of #34, which could indeed be resolved by #40, though I think it's a reasonable default to include docstrings in the report somewhere.
