### ISSUE TITLE
Add (or move) self-contained-html option to the INI configuration file (pytest.ini)

### ISSUE THREAD

**Issue by harmin-parra** [pytest-dev/pytest-html#719]
As discussed in the comments of https://github.com/pytest-dev/pytest-html/issues/521, I would love to be able to set the `self-contained-html `option in the INI file.

I guess the fix would only require the addition of this piece of code:

```
parser.addini(
    "self-contained-html",
    type="bool",
    default=False,
    help="create a self-contained html file.",
)
```
The question would be:

Should the INI option name be identical to the command-line option (`self-contained-html`) ?
or should the dash be replaced by underscore (`self_contained_html`) ?

**Comment by BeyondEvil** [comment]
You can already achieve this by using `addopts`.

```ini
[pytest]
addopts =
    --self-contained-html
```
