### ISSUE TITLE
xfailed tests are labeled "unexpected failures"

### ISSUE THREAD

**Issue by lodagro** [pytest-dev/pytest-html#729]
xfailed tests are labeled "unexpected failures" while these are "expected failures"

https://github.com/pytest-dev/pytest-html/blame/3e21601f49cc30dbdb0e06ed79c146d816dd5b09/src/pytest_html/report_data.py#L28

**Comment by wayne-manselle-apex** [comment]
Adding an example of the result in a report
![image](https://github.com/pytest-dev/pytest-html/assets/110860614/3b7ef535-26ba-405a-9706-a954fbdfc03f)

**Comment by jeffwright13** [comment]
Nobody expects the Unexpected Failure!
<img width="442" alt="Screenshot 2023-09-07 at 12 23 42 PM" src="https://github.com/pytest-dev/pytest-html/assets/4308435/f389b080-110e-4b4f-a17d-379056b4b6fb">

**Comment by BeyondEvil** [comment]
Oh noes! 🙈 

Thanks for reporting! Will fix asap.
