### ISSUE TITLE
TypeError: sequence item 0: expected str instance, div found

### ISSUE THREAD

**Issue by shaobo-zhang-senscomm** [pytest-dev/pytest-html#736]
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/_pytest/main.py", line 271, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/_pytest/main.py", line 325, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/_pytest/main.py", line 350, in pytest_runtestloop
INTERNALERROR>     item.config.hook.pytest_runtest_protocol(item=item, nextitem=nextitem)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_callers.py", line 152, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_result.py", line 114, in get_result
INTERNALERROR>     raise exc.with_traceback(exc.__traceback__)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/_pytest/runner.py", line 114, in pytest_runtest_protocol
INTERNALERROR>     runtestprotocol(item, nextitem=nextitem)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/_pytest/runner.py", line 133, in runtestprotocol
INTERNALERROR>     reports.append(call_and_report(item, "call", log))
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/_pytest/runner.py", line 226, in call_and_report
INTERNALERROR>     hook.pytest_runtest_logreport(report=report)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_hooks.py", line 493, in __call__
INTERNALERROR>     return self._hookexec(self.name, self._hookimpls, kwargs, firstresult)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_manager.py", line 115, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_callers.py", line 113, in _multicall
INTERNALERROR>     raise exception.with_traceback(exception.__traceback__)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pluggy/_callers.py", line 77, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pytest_html/basereport.py", line 250, in pytest_runtest_logreport
INTERNALERROR>     if self._report.add_test(data, report, processed_logs):
INTERNALERROR>   File "/home/scm/project/.env/lib/python3.10/site-packages/pytest_html/report_data.py", line 139, in add_test
INTERNALERROR>     test_data["log"] = _handle_ansi("\n".join(logs))
INTERNALERROR> TypeError: sequence item 0: expected str instance, div found

pytest-html: 4.0.1
pytest: 7.4.2
env: Ubuntu 22.04.2 LTS, 5.15.0-60-generic, x86_64

download pytest-html to 3.2.0, It is good.

**Comment by RonnyPfannschmidt** [comment]
It seems there's a custom hook adding data using py.xml which is not supported in 4.x

Do you have custom additions to the html report

**Comment by shaobo-zhang-senscomm** [comment]
@RonnyPfannschmidt 
Yes, I have custom additions.
Previous code may raise error.
`from py.xml import html
@pytest.hookimpl(optionalhook=True)
def pytest_html_results_table_html(report, data):
    if report.passed:
        del data[:]
        data.append(html.div('No log output captured.', class_='empty log'))
    if report.failed:
        del data[:]
        data.append(html.div(report.longreprtext, class_='log'))`

I change it as below
`@pytest.hookimpl(optionalhook=True)
def pytest_html_results_table_html(report, data):
    if report.passed:
        del data[:]
        data.append("<div class='empty log'>No log output captured.</div>")
    if report.failed:
        del data[:]
        data.append(f"<div class='log'>{report.longreprtext}</div>")`
There is no error raised. 
But there is still an issue. When report.passed, the log is not empty, some fixture log in the report. How to set the log empty?

**Comment by BeyondEvil** [comment]
I think what the issue is here.

You're probably seeing the "teardown" logs, correct?

The solution here is not straight forward, as there are multiple use-cases to account for.

The reason this wasn't an issue in previous versions where the "teardown" log wasn't added - a bug basically.

I'll need to think a bit about how to solve this.

**Comment by shaobo-zhang-senscomm** [comment]
@BeyondEvil 
Yes. i saw "teardown" logs.
Thanks
