### ISSUE TITLE
Version 4 shows all durations as 0ms

### ISSUE THREAD

**Issue by jeroenbrouwer** [pytest-dev/pytest-html#739]
All test durations in the html report show as 0ms whereas this used to give accurate results of the test durations.

![Screenshot 2023-09-18 at 12 44 41](https://github.com/pytest-dev/pytest-html/assets/13677331/45eaa0e0-99b9-4bfa-bb4f-f16eae74875f)

**Comment by BeyondEvil** [comment]
Looks like something indeed is off. 🤔 

81 tests in 2 minutes and 35 seconds should give an average of about 1,2 seconds per test.

Thanks for reporting!

**Comment by BeyondEvil** [comment]
I'm unsuccessful in repro:ing this.

```python
def test_duration():
    sleep(0.5)
    assert True
```

<img width="756" alt="Screenshot 2023-09-19 at 11 11 34" src="https://github.com/pytest-dev/pytest-html/assets/15611634/92fa71af-bf87-4da9-8b4e-89c631920eca">

Can you provide a minimal reproducible code sample?

**Comment by jeroenbrouwer** [comment]
This happens when the tests use a fixture, it used to be the case that the execution of the fixture was included in the test timing.

`from time import sleep
import pytest


@pytest.fixture(scope='session')
def has_slept():
    sleep(5)
    return True


def test_sleep(has_slept):
    assert has_slept
`

Results for version 4
![image](https://github.com/pytest-dev/pytest-html/assets/13677331/767b6ef3-371b-4550-b1da-8682af7fc032)

Results for version 3
![image](https://github.com/pytest-dev/pytest-html/assets/13677331/9db578bd-7cdf-4b8d-a52f-268da69ee1b8)

**Comment by BeyondEvil** [comment]
Ah, I see. Thanks for clarifying!
