### ISSUE TITLE
Retaining ANSI colors for logging level in html report

### ISSUE THREAD

**Issue by premkarat** [pytest-dev/pytest-html#74]
Currently I use ANSI colors for logger levels (info, debug etcc.) and it comes up nicely in console. However this is not retained in final html reports while using pytest-html.

The results output shows something like this.

----------------------------- Captured stderr call -----------------------------
[32m[INFO][0m INFO messages[0m 
[36m[DEBUG][0m DEBUG messages[0m 
[31m[ERROR][0m ERROR messages[0m

Is there a way to retain the color codes shown up in console.

pytest-html is really a fantastic plugin!!

**Comment by davehunt** [comment]
Interesting idea - perhaps we could use something like [ansi2html](https://pypi.python.org/pypi/ansi2html/).

**Comment by premkarat** [comment]
Dave,
Thank You for considering this use case. (its quite an imp one for us). I have no clue on html  libraries but I did gave a shot since we need this feature badly. I request your review on this patch. Since this is my first attempt, there is a good chance that i might have overlooked something.

I have extensively tested this and am attaching a test log for your reference. 

PFA the patch and test logs.

If you accept the patch, i will request for a pull.

[0001-Add-ANSI-support-in-html-report.txt](https://github.com/pytest-dev/pytest-html/files/464472/0001-Add-ANSI-support-in-html-report.txt)

[test-result.zip](https://github.com/pytest-dev/pytest-html/files/464480/test-result.zip)

`

**Comment by davehunt** [comment]
Thanks for the patch @premkarat - I've invited you to collaborate on this repository so I can set you as the assignee.

**Comment by davehunt** [comment]
Merged in https://github.com/pytest-dev/pytest-html/commit/24e169d9a4b1ab0d4018442582a96af8034ea945

**Comment by fenchu** [comment]
Was this ever fixed?, I still see:
```
[35mDEBUG   [0m tools.selenium:selenium.py:166 type:<class 'selenium.webdriver.chrome.webdriver.WebDriver'>
[32mINFO    [0m tools.conftest.py:conftest.py:138 creating directory:test12
```

**Comment by fenchu** [comment]
You need to install ansi2html to get it to work, nice

**Comment by heaventud** [comment]
Hi,
why it hasn't implemented for sections, that being added into longrepr too?
In our case, we hide excess test debug info, using **show-capture** option, but in order to output some details for error, use custom section in longrepr. Its no problem to color that in terminal, but in html report it doesn't work.

**Comment by BeyondEvil** [comment]
> Hi,
> why it hasn't implemented for sections, that being added into longrepr too?
> In our case, we hide excess test debug info, using **show-capture** option, but in order to output some details for error, use custom section in longrepr. Its no problem to color that in terminal, but in html report it doesn't work.

Please open a new issue, preferably with a reliable way to reproduce. Thanks! @heaventud
