### ISSUE TITLE
Strings in angle brackets are deleted from report

### ISSUE THREAD

**Issue by gscelsi** [pytest-dev/pytest-html#740]
Any string enclosed in angle brackets "<>", where the first character after the opening bracket is not blank, is removed from the output html report. Sometimes strange effects also occur, as it is the case in example #8 with the insertion of a double-quotes character.

pytest-html v. 4.0.1
pytest 7.4.2

[pytest-html-bug.tar.gz](https://github.com/pytest-dev/pytest-html/files/12655312/pytest-html-bug.tar.gz)

**Comment by jeffwright13** [comment]
My guess: Angle brackets are what defines HTML tags, so what you are probably seeing is rendered HTML. If the code inside your angle brackets is not valid HTML it will just be ignored by the browser, making it seem like it just disappered.

**Comment by gscelsi** [comment]
> My guess: Angle brackets are what defines HTML tags, so what you are probably seeing is rendered HTML. If the code inside your angle brackets is not valid HTML it will just be ignored by the browser, making it seem like it just disappered.

I would expect `pytest-html` to quote any test output when inserting it into its own html code. Is that not the case?

**Comment by BeyondEvil** [comment]
> I would expect `pytest-html` to quote any test output when inserting it into its own html code. Is that not the case?

The boring answer is "it depends".

Can you share some code that I can use to repro what you're seeing? Preferably with a screenshot of what the result is.

**Comment by gscelsi** [comment]
I have already attached code to reproduce as well as html output from the code. On 19 Sep 2023, at 7:09 pm, Jim Brännlund ***@***.***> wrote:﻿

I would expect pytest-html to quote any test output when inserting it into its own html code. Is that not the case?

The boring answer is "it depends".
Can you share some code that I can use to repro what you're seeing? Preferably with a screenshot of what the result is.

**Comment by gscelsi** [comment]
I have already attached code to reproduce as well as html output from the code. 


> The boring answer is "it depends".
> 
> Can you share some code that I can use to repro what you're seeing? Preferably with a screenshot of what the result is.
