### ISSUE TITLE
[help] is it possible to generate report after all tests run?

### ISSUE THREAD

**Issue by Mmajonez** [pytest-dev/pytest-html#742]
I just updated pytest-html from version 2 and the report is generated right after tests start - is there a flag or other way to disable generating empty reports with reload and wait for all data?

**Comment by jeffwright13** [comment]
I'm struggling to understand why that's desirable. Can you give us more context on your use-case?

**Comment by Mmajonez** [comment]
It's included in my Jenkins flow and that was an easy method for checking if tests already finished. I guess I can  do without, but I wanted to check first if additional work is needed. From your answer I can assume that generating report at the beginning is the only option, so thank you for fast reply

**Comment by jeffwright13** [comment]
Yeah, different plugins do things differently. My own plugin generates a
HTML report only after all the tests are done, but pytest-html starts at
the beginning of tests. This is actually an advantage in some ways; at
least in v4.0, you can open the report and start seeing results in
realtime. The results update as they stream from Pytest and you can refresh
it at any point to get the latest results.

It took me writing *two* plugins to do that. :-)

Anyway, I'm sure you can find a different trigger to signal your Jenkins
job that Pytest is done. I did a quick google search and found this, which
might be something you can use:
https://github.com/adamchainz/pytest-is-running
