### ISSUE TITLE
main.py: error: unrecognized arguments: — user data-dir

### ISSUE THREAD

**Issue by OGTSP** [pytest-dev/pytest-html#748]
While trying to run DeepFaceLive main.py: error: unrecognized arguments: — user data-dir "C:\Users\ezeri\Desktop\DeepFaceLive-Master i have the error below

main.py: error: unrecognized arguments: — user data-dirmain.py: error: unrecognized arguments: — user data-dir C:\Users\ezeri\Desktop\DeepFaceLive-Master

**Comment by RonnyPfannschmidt** [comment]
Please use code blocks to show the output and include the command you ran,

With the provided information there's nothing we can do to help

**Comment by OGTSP** [comment]
> Please use code blocks to show the output and include the command you ran,
> 
> With the provided information there's nothing we can do to help

I do not know how to run code blocks
The command  i run is- python main.py run DeepFaceLive — user data-dir C:\Users\ezeri\Desktop\DeepFaceLive-Master

**Comment by RonnyPfannschmidt** [comment]
Code Blocks Are a feature of GitHub to format things that are code or script output in a readable manner

As the main.py command seems to be a custom script,I fail to see how it's related to pytest-html

**Comment by blaq6ix** [comment]
hello please i have the same issue, i want to know how you solved it

**Comment by RonnyPfannschmidt** [comment]
Closing due to the affected people not providing enough information to solve this

**Comment by UMACDONALD1** [comment]
usage: main.py [-h] {run,dev,train} ...
main.py: error: unrecognized arguments: UPDATES\Desktop\SYSTEM SOFTWARE\DeepFaceLive-master


im having the above error on anaconda when trying to run deepfacelive

**Comment by UMACDONALD1** [comment]
i run anaconda on administrator mode but it cant locate file pat saved in my pc

python: can't open file "C:\\Users\\FRESHMAYOR'S UPDATES\\Downloads\\DeepFaceLive-master\\main.conda": [Errno 2] No such file or directory
