### ISSUE TITLE
Captured stdout in a subtest (pytest-subtests) is not displayed properly

### ISSUE THREAD

**Issue by yugokato** [pytest-dev/pytest-html#750]
Captured stdout in a subtest is not displayed as expected. Tested with v3.2.0 and v4.0.2 - both have the issue in a different way. Also the issue behavior changes depending on the `--capture` option value. I tried `fd` (the default value) and `tee-sys`.  Only v3.2.0 with `--capture tee-sys` seems to work as expected.

- Test code to reproduce:
```
def test_something(subtests):
    print("main test")

    with subtests.test("subtest"):
        print("sub test")
```

- Results:

  - v3.2.0

      1.  command: pytest --html fd_3.2.0.html
      -> Captured stdout from the subtest is missing
      2. command: pytest --html tee-sys_3.2.0.html --capture tee-sys
      -> Looks good
  - v4.0.2
      1. command: pytest --html fd_4.0.2.html
      -> main test and subtest are displayed as separate tests. One has captured stdout from the main test, the other has captured stdout from the subtest
      2. command: pytest --html tee-sys_4.0.2.html --capture tee-sys
      -> main test and subtest are displayed as separate tests. One has no captured stdout, the other has captured stdout from both main test and subtest

![fd_3 2 0](https://github.com/pytest-dev/pytest-html/assets/15665210/1d0415f0-2873-4490-9a0e-ce505da6cccc)
![tee-sys_3 2 0](https://github.com/pytest-dev/pytest-html/assets/15665210/08c1c9df-ba0c-4010-b831-fb93c7d293e6)
![fd_4 0 2](https://github.com/pytest-dev/pytest-html/assets/15665210/8c6ece2a-2d59-44a3-bd43-973921a0c262)
![tee-sys_4 0 2](https://github.com/pytest-dev/pytest-html/assets/15665210/01ba50bc-875b-4248-9428-564f0c62a352)

**Comment by jeffwright13** [comment]
Is this an issue with pytest-html, or with pytest in general? I haven't used `pytest-subtests` before, so maybe I don't know what to expect as its output, but I created a new subdirectory and new venv (3.10.5), copied your reproduction code in there into a file named `test_subtests.py`, and ran `pytest -v -rA`. I don't see any subtest output on console, only output from the main test. Should we expect to see a separate entry in the PASSES section?

```
(test-subtest) ~/coding/test_subtests pytest -v -rA
================================================= test session starts ==================================================
platform darwin -- Python 3.10.5, pytest-7.4.2, pluggy-1.3.0 -- /Users/jwr003/coding/test_subtests/venv/bin/python
cachedir: .pytest_cache
rootdir: /Users/jwr003/coding/test_subtests
plugins: subtests-0.11.0
collected 1 item

test_subtests.py::test_subtests [subtest] SUBPASS                                                                [100%]
test_subtests.py::test_subtests PASSED                                                                           [100%]

======================================================== PASSES ========================================================
____________________________________________________ test_subtests _____________________________________________________
------------------------------------------------- Captured stdout call -------------------------------------------------
main test
=============================================== short test summary info ================================================
PASSED test_subtests.py::test_subtests
========================================= 1 passed, 1 subtests passed in 0.02s =========================================
(test-subtest) ~/coding/test_subtests
```
