### ISSUE TITLE
Missing collection errors in pytest-html v4

### ISSUE THREAD

**Issue by akhilramkee** [pytest-dev/pytest-html#755]
Thanks for the rewrite and a revamped report in the pytest-html!

I noticed that the collection errors are not reported as part of pytest-html v4 but they were reported till pytest-html==3.2.0

Reproducer:

**test_sample.py**
```
import pytest

raise ImportError("Non existent module")
```

Run:

```
pytest test_sample.py --html=~/tmp/generated_html.html
```

---

**pytest-html == 3.2.0**:

![image](https://github.com/pytest-dev/pytest-html/assets/31619526/bd28f506-6aff-49f4-9878-c5303d686d0f)

**pytest-html == 4.0.3rc0**:

![image](https://github.com/pytest-dev/pytest-html/assets/31619526/79712e11-a35e-461c-a043-4592f5dddd6c)

---

Looking at the codebase, I can see that `pytest_collectreport` got missed out during the rewrite, so maybe adding that back should fix this.

**Comment by akhilramkee** [comment]
One more for `pytest-html 4.0.3` :) - @BeyondEvil

**Comment by BeyondEvil** [comment]
Oh, nice! We had indeed missed that.

Thanks for bringing it up!

**Comment by BeyondEvil** [comment]
Mind checking the [PR](#756) @akhilramkee ?
