### ISSUE TITLE
Not specifying a report name causes test file to be overwritten with html report contents

### ISSUE THREAD

**Issue by silne30** [pytest-dev/pytest-html#76]
# Steps to reproduce: 
Test assumes that you already have pytest-selenium installed into your virtualenv. 

Create a simple test called test_debug_pytest_html.py

```python
import pytest


class TestDebugPytestHtml(object):

    @pytest.mark.capabilities(marionette='true')
    def test_user_can_log_in(self, selenium):
        selenium.get('http://www.mozilla.org')
        assert selenium.title == 'We love Firefox!'
```

Now run this test from the command `py.test --driver Firefox --html test_debug_pytest_html.py` 

**Expected result**: Run test with a report written to some file name like report.html

**Actual Result**: The html report is appended to my python test file.

**Comment by davehunt** [comment]
The `--html` command line option takes a path argument for the report to be written. Your command line is giving it the path of an existing python file, so it is being replaced with the report. What I expect you want to do it something like:

```
py.test --driver Firefox --html results.html test_debug_pytest_html.py
```

Closing as working as expected.
