### ISSUE TITLE
Split basereport.py/BaseReport.pytest_runtest_logreport  into smaller bites

### ISSUE THREAD

**Issue by Stefanhg** [pytest-dev/pytest-html#762]
`pytest_runtest_logreport `method contains a lot of subparts that are used to build the actual report.
By splitting these method into submethods of either another class or the same class then it is easier for other to hook onto the methods and modify the result. This allows for customizing the report to different needs or other plugins can hook onto the methods allowing for more custom report options.

Example:
`cells = [...]` 
becomes
`cells = self.generate_cells() `

It makes the code cleaner, reduces `pytest_runtest_logreport `length and allows other plugins to override/super load the `generate_cells `method

**Comment by Stefanhg** [comment]
@BeyondEvil Now that I am looking into this.
Is it not possible to run the tests in PyCharm? It keeps saying the app.js is missing

**Comment by BeyondEvil** [comment]
> @BeyondEvil Now that I am looking into this. Is it not possible to run the tests in PyCharm? It keeps saying the app.js is missing

You need to run:

```sh
$ npm install && npm run build
```

That will generate the `app.js` file.

I use Hatch for development, so that is automatically handled (or should be at least).

**Comment by Stefanhg** [comment]
@BeyondEvil Seems like it was related to ChromeDriver as I was running a newer version of Chrome.
Now it runs the test but not report is generated in temp folder.

**Comment by Stefanhg** [comment]
In my case I switched to pytest-reporter instead of HTML as it gave me a better control of the report. If somebody has a need for this task to be done feel free to reopen it. Closing it for now.
