### ISSUE TITLE
pytest_html_results_table_row hook is called twice when running tests

### ISSUE THREAD

**Issue by gregtwice** [pytest-dev/pytest-html#786]
When running tests, i get the following error, same as in issue #782 
```
INTERNALERROR>     if "sortable" in self._report.table_header[index]:
INTERNALERROR>                      ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
INTERNALERROR> IndexError: list index out of range
```

The sample code is take verbatim from the [documentation](https://pytest-html.readthedocs.io/en/latest/user_guide.html#modifying-the-results-table)

When investingating the error and adding logging to the hook, i can see that it is called twice during the same test.
When inspecting the values of cells and `cells` and `self._report.table_header` in basereport.py in `_hydrate_data`, I see that the length of `cells` is 8 when `self._report.table_header` is 6. as the code is iterating on cells, this triggers an index error.

Has this ever happened to anyone else ?

here is the sample code
```python
def pytest_html_results_table_header(cells):
    cells.insert(2, "<th>Description</th>")
    cells.insert(1, '<th class="sortable time" data-column-type="time">Time</th>')


def pytest_html_results_table_row(report, cells):
    description = report.description.replace(" ", "&nbsp").replace("\n", "<br />")
    cells.insert(2, f"<td>{description}</td>")
    cells.insert(1, f'<td class="col-time">{datetime.utcnow()}</td>')
    print(cells)


@pytest.hookimpl(hookwrapper=True)
def pytest_runtest_makereport(item, call):
    outcome = yield
    report = outcome.get_result()
    report.description = str(item.function.__doc__)
```

Here is the result of the `print(cells)` statement

```
['<td class="col-result">Passed</td>', '<td class="col-testId">test_suite_setUp::setup</td>', '<td class="col-duration">0 ms</td>', '<td class="col-links"></td>', '<td>None</td>', '<td class="col-time">2023-12-19 17:19:07.301758</td>']
['<td class="col-result">Passed</td>', '<td class="col-testId">test_suite_setUp::setup</td>', '<td class="col-duration">0 ms</td>', '<td class="col-links"></td>', '<td>None</td>', '<td class="col-time">2023-12-19 17:19:07.301758</td>', '<td>None</td>', '<td class="col-time">2023-12-19 17:19:07.302751</td>']
```
printing the content of `report.call` when filtering on report.when == "call" also gives 'setup' twice and then 'call' twice

**Comment by gregtwice** [comment]
I found the answer, it was a weird bug due to the pwd of the working directory and the windows directory names.

Pytest was registering two conftests.py that were located in the same directory, but under two different paths, One with the windows path and one with the pwd that used the path with a different name:

```
PLUGIN registered: <module 'conftest' from 'C:\\Tests\\conftest.py'>
PLUGIN registered: <module 'conftest' from 'C:\\tests\\conftest.py'>
```

changing the path to the default windows one fixed the issue.
Closing the issue.

**Comment by bayannagetteboina-eaton** [comment]
test file

from embedded.protocols.rest.uris_payloads_and_response import URIs
from px_green.tests.functional_test.rest.support.user_management import UserSupport
from px_green.utilities import general_utils
from px_green.utilities.rest_utils import convert_to_dict, key_pass_value
from py.xml import html
import pytest
import logging


class TestRESTBitfield(UserSupport):
    """Class to validate REST Firmware processor functionalities for all methods."""

    supported_methods = None
    path_string = "Bitfield"
    key_pass_list = ["", "Bitfield"]
    test_3 = None

    @staticmethod
    def get_test_name():
        """Get Test Name."""
        return "Test Case to validate REST bitfield."

    @staticmethod
    def get_feature_name():
        """Get Feature Name."""
        return "REST"

    @staticmethod
    def get_test_desc():
        """Get Test Description."""
        return "Test Case to validate REST Bitfield /rs/param/{x}/bitfield for all methods."

    @pytest.fixture(scope='class', autouse=True)
    def class_setup_teardown(self, request, user_support_setup_teardown):
        """
        """
        print("Fixture setup started")
        request.cls.rest_uri = URIs.rs_bitfield
        request.cls.supported_methods = self.methods_supported(self.path_string)

        test3 = self.console.read_reg_value("DCI_REST_ROLE_4_NAME")
        logging.info(f"initial_DCI_REST_ROLE_4_NAME1 : {test3}")
        print(f"initial_DCI_REST_ROLE_4_NAME1 : {test3}")
        request.cls.test3 = test3  # Store initial value in the class

        yield

        test3_latest = self.console.read_reg_value("DCI_REST_ROLE_4_NAME")
        logging.info(f"latest_DCI_REST_ROLE_4_NAME2 : {test3_latest}")
        print(f"latest_DCI_REST_ROLE_4_NAME2 : {test3_latest}")
        request.cls.test3_latest = test3_latest  # Store latest value in the class

        # Store values in the config object
        if not hasattr(request.config, 'test_values'):
            request.config.test_values = {}
        request.config.test_values['test3'] = test3
        request.config.test_values['test3_latest'] = test3_latest
        print("request.config:", request.config)
        print("Fixture setup completed")

    def test_abc(self):
        assert 1 == 1
        
        
        
  conftest.py
  
  


import pytest

@pytest.hookimpl(tryfirst=True)
def pytest_configure(config):
    print("1111111111111111", config, type(config))
    if not hasattr(pytest, 'test_values'):
        config.test_values = {}
    print("11>>:", config.test_values)

@pytest.mark.optionalhook
def pytest_html_results_summary(prefix, summary, postfix):
    # Access the stored values from the config object
    print("222222222222222222")
    test_values = getattr(pytest, 'test_values', {})
    print("test_values:", test_values)
    test3_value = test_values.get('test3', 'N/A')
    test3_latest_value = test_values.get('test3_latest', 'N/A')

    summary.append(f"initial_DCI_REST_ROLE_4_NAME1: {test3_value}")
    summary.append(f"latest_DCI_REST_ROLE_4_NAME2: {test3_latest_value}")
    
    
    
    valyes of test3 and test+latest is not coming in pytest_html_results_summary
