### ISSUE TITLE
[Regression] The generated html can not be shown properly in emails.

### ISSUE THREAD

**Issue by taozuoqiao** [pytest-dev/pytest-html#788]
After upgraded to V4, the generated html can not be shown properly in email when sent via python:
The tables  can not be shown, only section titles left.

![image](https://github.com/pytest-dev/pytest-html/assets/18346451/d18350b4-da00-4e17-9040-8190186f4939)

**Comment by BeyondEvil** [comment]
Yes, this is unfortunately a side-effect of the new client side rendering.

One possibility, is to first render the report with Selenium and then send it.

That's how we do it in the integration tests. BeautifulSoup is only needed to interact with the HTML.
