### ISSUE TITLE
node.slaveoutput has no key 'environment' when used with xdist and cygwin

### ISSUE THREAD

**Issue by engelmav** [pytest-dev/pytest-html#79]
I know, this is a horrendous configuration; it's what we're working with.

On line 73 of `pytest_html/plugin.py` the key `environment` is not present in`node.slaveoutput`. As the title says, this condition is reached when executing pytest with xdist over multiple ssh hosts, that themselves are running ssh daemons with cygwin. I've been able to get around this using:

```
 73         if 'environment' not in node.slaveoutput:
 74             node.slaveoutput['environment'] = None
```

But I am this certain causes issues in other circumstances, e.g. when trying to access the `environment` attribute when generating reports. I could instead simply add 'Not Found'... Would you accept a PR with this? I can also give the xdist guys a heads up.

**Comment by RonnyPfannschmidt** [comment]
i have no real idea what you mean, please show an example that makes it clear

(also i am the current xdist guy)

**Comment by davehunt** [comment]
Environment has been replaced by pytest-metadata integration. If you're still having issues please open a new issue with further details against the appropriate plugin.
