### ISSUE TITLE
My Appium tests fail due an error: binascii.Error: Incorrect padding

### ISSUE THREAD

**Issue by tking16** [pytest-dev/pytest-html#805]
I'm running parallel Appium tests which generate reports using pytest-html, since migrating to parallel runs the tests seems to keep failing with this error I've never seen before. Not sure what's causing it but for further context the appium tests are running using Selenium Grid, whether I use multiple iOS simulators or just one single sim the error will appear, this never happened before implementing Selenium Grid.

Github actions output ⬇️
<img width="1134" alt="Screenshot 2024-04-05 at 12 06 03" src="https://github.com/pytest-dev/pytest-html/assets/13576824/841590f8-c979-4d09-8361-b3f66d3fceab">

[selenium_grid.log](https://github.com/pytest-dev/pytest-html/files/14887889/selenium_grid.log)
[appium.log](https://github.com/pytest-dev/pytest-html/files/14887890/appium.log)
[node.log](https://github.com/pytest-dev/pytest-html/files/14887887/node.log)
[appiumlogDevice3.log](https://github.com/pytest-dev/pytest-html/files/14887888/appiumlogDevice3.log)
Any help is appreciated

Pytest-html version: 4.1.1

**Comment by tking16** [comment]
A bit more information I should have posted, the reports are being generated using functions from a repo called Pytest-Appium, which can be found [here](https://github.com/GlobalRadio/pytest-appium/blob/main/pytest_appium/html_reporting.py)

**Comment by BeyondEvil** [comment]
Well, for starters, the output you provided is from pytest-html 3.x and not 4.x.

There's no `_append_image` function in 4.x.

Start there.

If that doesn't help, you'll have to narrow it down a lot more. There's too many moving parts, especially with Selenium Grid and Appium, for me to have any chance to repro this.

So either narrow it down significantly, or set up a project (or some other way) for me to reproduce it.

**Comment by tking16** [comment]
Thanks @BeyondEvil, I realised I didn't lock down the version, so it's definitely on 3.2.0 now. Seems the error doesn't happen when I use just one single device, my theory is that because I'm using 3 different simulators of different screen sizes, it may be getting confused as what aspect ratio to capture the screenshot with, hence the `binascii.Error: Incorrect padding`.

To try and fix it I'm gonna add try and catch statements to both `_gather_screenshot` & `_gather_video` for our [plugin](https://github.com/tking16/pytest-appium/blob/master/pytest_appium/html_reporting.py)

**Comment by BeyondEvil** [comment]
I would encourage you to try out 4.x because even if you _do_ find an issue with the plugin, it's unlikely we'll backport a fix to 3.x. @tking16

**Comment by tking16** [comment]
@BeyondEvil thanks will do, you mentioned in an earlier response that "There's no _append_image function in 4.x.". What would be the v4 equivalent for attaching screenshots/videos to a html report then?

**Comment by BeyondEvil** [comment]
@tking16 

Take a look at https://pytest-html.readthedocs.io/en/latest/user_guide.html#extra-content

That really should’ve been used in 3.x as well, as ”_append..” is a private function.

**Comment by tking16** [comment]
I think I've managed to resolve my initial issue with the Base64 encoding. Basically what was happening was the Appium server had a 10 second timeout which was killing the driver, stopping a lot of the pytest-appium functions from working properly. Thanks for the help though, I'll close this ticket now

**Comment by BeyondEvil** [comment]
Happy you found and fixed the issue! ☺️
