### ISSUE TITLE
pytest-html 4.x.x incompatible with pytest-metadata 3.1.1 ?

### ISSUE THREAD

**Issue by supermete** [pytest-dev/pytest-html#809]
Hello,

I was recently still using pytest 7.3.1 and upgraded pytest-html from 3.2.0 to 4.1.1.
Without changing anything else, it failed to generate the report with the following error:

```
INTERNALERROR>   File "C:\FSBMS\tools\main\environment\python\Python310\lib\site-packages\pytest_html\basereport.py", line 291, in _process_report
INTERNALERROR>     self._report.add_test(data, report, outcome, processed_logs)
INTERNALERROR>   File "C:\FSBMS\tools\main\environment\python\Python310\lib\site-packages\pytest_html\report_data.py", line 140, in add_test
INTERNALERROR>     test_data["log"] = _handle_ansi("\n".join(logs))
INTERNALERROR> TypeError: sequence item 0: expected str instance, table found
```

I have the full log if necessary. I didn't prepare a sample code because I don't think it's relevant, what happens is probably not related to the content of the test.
As you can see I'm using python 3.10.

Upgrading pytest to 8.1.1 solved the issue, but I figured it's still worth noting since I couldn't find any incompatibility note in the doc.

**Comment by supermete** [comment]
After some more fiddling, the incompatibility might come from pytest-metadata and pytest... it seems pytest-metadata doesn't support pytest >= 8.0.0 yet, and that makes the report generation fail for some reason.

**Comment by BeyondEvil** [comment]
> After some more fiddling, the incompatibility might come from pytest-metadata and pytest... it seems pytest-metadata doesn't support pytest >= 8.0.0 yet, and that makes the report generation fail for some reason.

Thanks for bringing this to my attention! I maintain pytest-metadata as well. Will look into it.

**Comment by supermete** [comment]
@BeyondEvil turns out that the issue came from how I inserted data in pytest_html_results_table_html.
With previous versions, I was using py.xml.html to insert a table in data like this:

```
def pytest_html_results_table_html(report, data):
    data.insert(0, html.table( ... ))
```

That used to work but now it's not, it expects a string instead. Converting html.table into a string gets rid of the error.

I still can't have a proper report though. The only result I'm getting is an empty table with a green button saying that "There are still tests running". While I can't clearly see in the stdout that the tests are finished. I will open a separate issue.

**Comment by BeyondEvil** [comment]
> I still can't have a proper report though. The only result I'm getting is an empty table with a green button saying that "There are still tests running". While I can clearly see in the stdout that the tests are finished. I will open a separate issue.

Please check the browser console for any issues/errors.
