### ISSUE TITLE
"xpassed" marked as "passed"

### ISSUE THREAD

**Issue by jfthuong** [pytest-dev/pytest-html#83]
Hi,

I have a test which is "xpassed", reported as such by pytest and recorded as "passed" in the html report.
![report_xpassed](https://cloud.githubusercontent.com/assets/1401809/19995648/4b402d14-a294-11e6-9901-a5c2438c124e.png)

I have the following test file

```python
import pytest
def test_failed():
	assert 3 + 4 == 6

def test_passed():
	assert 4 + 4 == 8

@pytest.mark.xfail(reason="test xfailed")
def test_xfailed():
	assert False

@pytest.mark.xfail(reason="test xpassed")
def test_xpassed():
	assert True
```

**Comment by davehunt** [comment]
This is working for me. Please provide details of the versions of pytest and pytest-html in use.

**Comment by jfthuong** [comment]
pytest-3.0.2
pytest-html-1.10.0

**Comment by davehunt** [comment]
Please upgrade to pytest-html 1.10.1. As the [release notes](https://github.com/pytest-dev/pytest-html/blob/master/CHANGES.rst) states this includes "Fix issue with unexpected passes not being reported in pytest 3.0"

**Comment by jfthuong** [comment]
It's working. Thanks.

Good job for the many updates: it's nice to see a project so active.

**Comment by davehunt** [comment]
You're welcome. Thanks for using the plugin and reporting your issue! 😄
