### ISSUE TITLE
Add plugin version number to report generation header

### ISSUE THREAD

**Issue by davehunt** [pytest-dev/pytest-html#86]
At the moment the report generation header looks something like:

> Report generated on 08-Nov-2016 at 11:33:07

It would be useful when diagnosing problems if the plugin name was mentioned with a link to the project on PyPI, and the version was included such as:

> Report generated on 08-Nov-2016 at 11:33:07 by [pytest-html](https://pypi.python.org/pypi/pytest-html) v1.11.0

**Comment by denisra** [comment]
Hello @davehunt, I can help with this one. Will make a pull request shortly.

**Comment by RonnyPfannschmidt** [comment]
it should perhaps include all plugin distributions

**Comment by davehunt** [comment]
> it should perhaps include all plugin distributions

I think that's a further enhancement, to add that information to the environment section. Possibly we could save this for the pytest-environment plugin that I'm planning.

**Comment by denisra** [comment]
@davehunt First time committing to the project, so forgive me for any mistakes. 
And please let me know if you need me to change anything.
