### ISSUE TITLE
Title of checkbox disappears when unchecked

### ISSUE THREAD

**Issue by vashirov** [pytest-dev/pytest-html#90]
![image](https://cloud.githubusercontent.com/assets/1745018/20598329/fb860ad6-b248-11e6-86bb-f8381410e3ec.png)

![image](https://cloud.githubusercontent.com/assets/1745018/20598332/0253f9cc-b249-11e6-80c3-8e46070e1c19.png)

Regression was introduced in 972058bb. Reverting changes for main.js returned previous behaviour.

**Comment by davehunt** [comment]
Thanks for raising this! Are you interested in working on the fix?

**Comment by vashirov** [comment]
Fix is a simple revert of changes done to main.js fitler_table by previous commit.
