### ISSUE TITLE
Report is generated and written to disk regardless of selenium_capture_debug

### ISSUE THREAD

**Issue by BeyondEvil** [pytest-dev/pytest-html#94]
In pytest.ini I have:

selenium_capture_debug = failure

However, pytest-html still generates a report if all tests pass. Same goes for if I set it to 'never'.

Now, in pytest-selenium#pytest_runtest_makereport(), it works as expected: the item.config.hook.pytest_selenium_capture_debug() is never called.

But, in plugin.py (pytest-html), pytest_runtest_logreport() and pytest_terminal_summary() are still called. I cannot find any checks for the ini config in pytest-html.

It all used to work as expected.

Versions:
pytest==3.0.5
pytest-selenium==1.6 (we can't run newer due to Selenium 3 requirement)
pytest-html==1.12.0

**Comment by BeyondEvil** [comment]
My hope was to provide a PR to fix it, but I'm not sure how the whole hooks.py thing works. I couldn't find any references to them in other files (apart from pytest_selenium.py and hooks.py)

**Comment by davehunt** [comment]
`selenium_capture_debug` is a feature of pytest-selenium that allows you to control when additional debug information is gathered for tests. By default, this will happen on failures, but sometimes it can be useful to do so when tests pass (though it does increase the size of the report considerably). I'm not sure what your expected outcome is, or how this worked previously. Could you provide more detail?

> we can't run newer due to Selenium 3 requirement

Selenium 3.x should be a drop-in replacement for 2.x... if you have issues upgrading could you provide details on this too?

**Comment by BeyondEvil** [comment]
Sorry for the late response @davehunt, I've been home sick.

So, from memory, this is how I remember it used to work:

You provide the --html commandline flag and in your ini file (in our case pytest.ini) you provide the 'selenium_capture_debug' flag. With set to 'failure' the combination of the two would only produce the report if there was a failure.

No, if I remember incorrectly and the way it works now is by design, then I apologise and you can close this issue.

Regarding pytest-selenium version, running any version higher than 1.6 does not work for us, since it requires a selenium-version higher than 2.53. Since geckodriver is still in beta (does not support ActionChains for example) we cannot move to Selenium/Webdriver 3.

Does that make sense?

**Comment by davehunt** [comment]
> Sorry for the late response @davehunt, I've been home sick.

Sorry to hear that. 🙁 

> Now, if I remember incorrectly and the way it works now is by design, then I apologise and you can close this issue.

I think you're remembering incorrectly, the option to only capture debug on failure in pytest-selenium should not prevent a HTML report from being generated.

> Regarding pytest-selenium version, running any version higher than 1.6 does not work for us, since it (pytest-selenium that is) requires a selenium-version higher than 3. Since geckodriver is still in beta (does not support ActionChains for example) we cannot move to Selenium/Webdriver 3.

You don't need to use GeckoDriver with Selenium 3.x, so you should be fine to upgrade. If you see issues then please file them against pytest-selenium and I can look into them.

**Comment by davehunt** [comment]
I'm going to close this, as I believe it's invalid.
